### ISSUE TITLE
Any plan to support apple silicon?

### ISSUE THREAD

**Issue by tixo** [kingToolbox/WindTerm#1004]
Any plan to support apple silicon?

**Comment by zhongzhichun** [comment]
This author has no m1 chip notebook computer, you can donate to him

**Comment by tixo** [comment]
> 

Do not talk about it, Please focus on the issue itself.

**Comment by tixo** [comment]
@zhongzhichun 
Don't talk about it, focus on the question itself.
> This author has no m1 chip notebook computer, you can donate to him

**Comment by kingToolbox** [comment]
Duplicate of #848 

Sorry for replying so late, I just got back from a business trip.

Since the `arm64` version of `Qt 5.15` will not be released until next year, there will be no `arm64` version of `WindTerm` for the time being. However, once `Qt` releases the `Qt 5.15 arm64` version, the `WindTerm arm64` version will also be released as soon as possible. Please stay tuned, thank you.

**Comment by tixo** [comment]
Hi,
I saw that the Qt 5.15.9 has released, and it support for macOS on ARM,  more details please visit https://www.qt.io/blog/commercial-lts-qt-5.15.9-released.
