### ISSUE TITLE
win10系统下打开某个session经常崩溃

### ISSUE THREAD

**Issue by ranbest** [kingToolbox/WindTerm#109]
win10系统下打开某个session经常崩溃，但我找不到具体日志在哪

**Comment by ranbest** [comment]
升级 最新版本，又不崩溃了

**Comment by kingToolbox** [comment]
It's hard to say why, but if the problem occurs again, I will follow up and solve it. Thank you.

**Comment by ranbest** [comment]
> It's hard to say why, but if the problem occurs again, I will follow up and solve it. Thank you.

如果出现突然崩溃现象。我怎么把日志文件发给你？另外，日志文件路径在哪

**Comment by kingToolbox** [comment]
Unfortunately, there is currently only session debug log (MenuBar - Mode - [Debug Mode](https://kingtoolbox.github.io/2020/07/21/debug_mode/)), and no crash report yet. There are plans to integrate `google/breadpad` in subsequent versions. If there is a crash, you only need to tell me the version used and the operation before the crash, usually these are enough to locate the problem.

**Comment by ranbest** [comment]
最近使用WindTerm经常崩溃，并且点击了debug mode没有任何反应。
win10系统，无法访问外网。
软件版本，最新 2.1 pre4
基本上任何命令操作都可能崩溃。。。
2.0版本的时候就没有出现过。

**Comment by hongnod** [comment]
Can kingToolbox read Chinese?

**Comment by kingToolbox** [comment]
Sorry, I am focusing on releasing [WindTerm_2.1.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) this weekend. Although it did not enhance robustness. I still recommend you to download and use, thank you.

Due to the development of `X/Y/Z Modem`, `Sync Input` and the `Master Password` issue, this version has been postponed many times. If you have seen the release logs of all the [prerelease versions](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease), you will know how big the changes are in this version. As a result, too many features have been added, and the factors of instability have increased. Now I have released the last prerelease version with new features. It's time to solve the stability. But not all issues will be resolved in `v2.1.0`, some will be fixed in the bugfix versions, like `v2.1.1` or `v2.1.2` and so on, to avoid affecting the release of the `MacOs` version of WindTerm.

BTW:
Although there will be no response when you click the [Debug Mode](https://kingtoolbox.github.io/2020/07/21/debug_mode/), once you start interacting with the server, all debugging information will be recorded in detail in the log file. You can upload the log here as an attachment, and I will analyze the log. No private information will be recorded in the log, including server address, user name, password, etc. The log is in plain text format, you can check and delete sensitive information before uploading. 

As for the language of the issue, I don’t mind using your native language. Normally I can understand or guess it, or I will use machine translation. But it’s better to use English, so that other uses can understand it, or avoid filing a same issues, thank you very much.

**Comment by ranbest** [comment]
> Sorry, I am focusing on releasing [WindTerm_2.1.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) this weekend. Although it did not enhance robustness. I still recommend you to download and use, thank you.
> 
> Due to the development of `X/Y/Z Modem`, `Sync Input` and the `Master Password` issue, this version has been postponed many times. If you have seen the release logs of all the [prerelease versions](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease), you will know how big the changes are in this version. As a result, too many features have been added, and the factors of instability have increased. Now I have released the last prerelease version with new features. It's time to solve the stability. But not all issues will be resolved in `v2.1.0`, some will be fixed in the bugfix versions, like `v2.1.1` or `v2.1.2` and so on, to avoid affecting the release of the `MacOs` version of WindTerm.
> 
> BTW:
> Although there will be no response when you click the [Debug Mode](https://kingtoolbox.github.io/2020/07/21/debug_mode/), once you start interacting with the server, all debugging information will be recorded in detail in the log file. You can upload the log here as an attachment, and I will analyze the log. No private information will be recorded in the log, including server address, user name, password, etc. The log is in plain text format, you can check and delete sensitive information before uploading.
> 
> As for the language of the issue, I don’t mind using your native language. Normally I can understand or guess it, or I will use machine translation. But it’s better to use English, so that other uses can understand it, or avoid filing a same issues, thank you very much.


thank you very much!  The crash problem seems to have been solved, and it doesn't happen frequently。

**Comment by kingToolbox** [comment]
There should still be bugs that can cause a crash, and I will continue to troubleshoot. If you experience a crash again, please let me know, thank you very much.

**Comment by kingToolbox** [comment]
A new version with `google/breadpad` integrated has just been released. Please download and use [WindTerm_2.1.0_Prerelease_6_MacOS_Portable](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease). 

If you encounter a crash again, you can submit the generated crash report in the current working directory, such as `8f9a5ae5-4ea2-170e-55e9b70e-05c9ab40.dmp`, as an attachment in the issue. I will analyze it and fix the problem. Thank you.
