### ISSUE TITLE
add new theme

### ISSUE THREAD

**Issue by ranbest** [kingToolbox/WindTerm#112]
can you add some new themes?

**Comment by kingToolbox** [comment]
Sorry, no new themes will be designed for the time being. There are still many features and bugs that need to be done.

However, I will provide methods and documents on how to customize the themes in subsequent versions, and create a new repo for sharing them, so that people with more art talents can design themes. For example, I think the [dracula theme](https://github.com/kingToolbox/WindTerm/issues/62) designed by @lpadula is better than mine. I think this would be a better method.

**Comment by ranbest** [comment]
ok ，your mind  is better

**Comment by kingToolbox** [comment]
Thank you for understanding.
