### ISSUE TITLE
Terminal.ClearScreen

### ISSUE THREAD

**Issue by huai168an** [kingToolbox/WindTerm#113]
Have been using the “ctrl + L” to clear the screen, today the use of the exception, did not modify the configuration file。
now, ctrl+alt+L to clear the screen, not lock screen。

“ctrl + L” action show
![image](https://user-images.githubusercontent.com/52577307/123731090-15764d00-d8ca-11eb-8a7e-de5c1a00fd63.png)

wind.keymaps is default
Bug or configuration file problem ?

release：WindTerm_2.1.0_Prerelease_5_Windows_Portable

**Comment by huai168an** [comment]
It's normal again, I don't know what I moved 。。。。: (

**Comment by kingToolbox** [comment]
From the description, I don’t know what happened too. But it doesn't matter, if it is a bug, it will definitely reappear. :smile:

For the configuration file, it is more recommended to modify `profiles/default.v10/user.config` instead of `global/wind.config`. In this way, there is no need to modify it again when upgrading to a new version. Please read [this comment](https://github.com/kingToolbox/WindTerm/issues/89#issuecomment-826561221) to learn more.

**Comment by kingToolbox** [comment]
This issue will be closed because it cannot be reproduced. Please reopen this issue if it is still valid. Thank you.
