### ISSUE TITLE
(feature request) customisable keyboard shortcuts would be handy

### ISSUE THREAD

**Issue by danmur** [kingToolbox/WindTerm#13]

**Comment by kingToolbox** [comment]
Thank you. Keyboard shortcuts are already customizable and you can read and modify WindTerm-Install-Path/global/wind.keymaps to bind any shortcut to any action you wanted. The setting interface will be provided in short future.

By the way, WindTerm also has a very powerful keyboard customization capability. It supports key sequence, when and where to match, and what to do when matched. For example:

The following keyboard configuration defines the action "Window.SplitViewHorizontally", which is defined in WindTerm-Install-Path/global/wind.actions, to be executed when the <Alt+W><Alt+H> keys are pressed in the view.
```json
  { "keys": "<Alt+W><Alt+H>",
    "when": "window.isScope('*.view')",
    "action": "Window.SplitViewHorizontally"
  },
```

The following keyboard configuration defines that the search pane is hidden when the \<Esc\> key is pressed in the view and when the search pane is visible.
```json
  { "keys": "<Esc>",
    "when": "window.isScope('.view') && window.activeKit.isPaneVisible('search')",
    "script": "() => { window.activeKit.hidePane('search') }"
  },
```

**The most outstanding thing is that WindTerm even supports using regular expressions to match keyboard sequences and supports group capture.** Based on this feature, WindTerm simulated almost all VIM keyboard sequences. For example:

The following keyboard configuration defines the navigation keys of Vim in the local mode by only one regular expression.
```json
  { "keys": "(?P<keys>\\d*([\\$\\(\\)\\+\\-\\^\\{\\}0bBeEGhHjklLMwW]|g[eEg]|z[jk]))",
    "modes": "command, local",
    "script": "(captures) => {
      let text = window.activeText;
      let position = text.movePosition(text.caretPosition, captures.keys);

      text.gotoPosition(position);
    }"
  }
```

So you can use { "keys" : "a{9}(?P\<count\>\\\\d+)" } instead of {"keys": "aaaaaaaaa123"} to match a 'a' that repeated 9 times and followed by a number. The capturing group 'count' can be referenced by 'captures.count' in the script. **It's the most powerful way of keyboard customization that has never been seen before.**

With the abilities mentioned above, one can easily customize handy keyboard shortcuts. Not only the keyboard shortcuts, but also almost everything in WindTerm, including protocols, terms, schemes, actions, menus, toolbars, colors, GUI and so on, is already customizable. More API and detailed documentation will be added in the future.

**Comment by danmur** [comment]
That's excellent, thank you! I'm perfectly happy editing the config file personally, a menu item to open it in an editor would be enough for most :).

**Comment by mzky** [comment]
How to add custom shortcut keys to execute custom commands or scripts ?

**Comment by kingToolbox** [comment]
@mzky 
Sorry, there is currently no api named `echo`, and `QuickBar` does not provide binding shortcut keys too, both of which will be provided in subsequent versions. Since the current issue has been closed, if you need the `echo` api, you can file a new issue. As for the shortcut key feature, there is already #180. Thank you.

**Comment by yueludanfeng** [comment]
Could you support shortcut customization via GUI ?

**Comment by pipSu** [comment]
> @mzky Sorry, there is currently no api named `echo`, and `QuickBar` does not provide binding shortcut keys too, both of which will be provided in subsequent versions. Since the current issue has been closed, if you need the `echo` api, you can file a new issue. As for the shortcut key feature, there is already #180. Thank you.

Do we have shortcut key settings for quick commands now? This is important to me.

**Comment by pipSu** [comment]
> @mzky Sorry, there is currently no api named `echo`, and `QuickBar` does not provide binding shortcut keys too, both of which will be provided in subsequent versions. Since the current issue has been closed, if you need the `echo` api, you can file a new issue. As for the shortcut key feature, there is already #180. Thank you.

Do we have shortcut key settings for quick commands now?
