### ISSUE TITLE
请尽快完全开源，不开源的ssh客户端不敢用啊

### ISSUE THREAD

**Issue by shinebay** [kingToolbox/WindTerm#149]
感谢作者开发这么好一款作品！

**Comment by 107295472** [comment]
破解的你怎么用的，这很安全了

**Comment by cd-yangling** [comment]
> 破解的你怎么用的，这很安全了

当你用私钥登陆服务器的情况下，谁知道闭源的ssh会不会偷盗你的私钥。这确实是很危险的。

**Comment by kingToolbox** [comment]
This is a very interesting question. In the past two years since WindTerm was publicly released, I have been asked this question from time to time, and I am very willing to discuss it. I often think about the following three questions, and I also want to know how you think about them.

1. Now most of the popular SSH clients are paid, and of course there is no source code. Why do most people choose to trust the commercial clients? 
2. Putty is open source, but does this mean that `putty.exe` is safe? I don't think so. I have seen many, especially the localized versions, such as the **Russian version** of `putty.exe`, **Chinese version** of putty.exe, etc., have viruses or backdoors. 
3. Shouldn't the safety of tools come only from actual use? For example, you can use a firewall to monitor whether a tool secretly uploads information to an illegal address. Or you can even use routing tables to limit the addresses that the tool can access. 

The second point is what I am most concerned about, and it's also one of the important reasons why I am not willing to open source completely. Many people do not have a good sense of security. If `WindTerm` is completely open source, I believe there will be a version with malicious code added like `putty`, and then some people will inevitably become victims. 

**If someone is worried that WindTerm is not open source and does not use it, I will lose at most one user who does not trust me and my tool. But if someone uses a maliciously modified WindTerm, then I hurt a user who trusts me and my tool. In comparison, the latter is more important to me.**

**Comment by kingToolbox** [comment]
In addition, I like open source, and many features of WindTerm benefit from the open source community. **I have always been grateful for this. So I will continue to open source part of the code in the future. 

1. Some useful classes or algorithms will be open source. 
2. Some core codes will be refactored into libraries, such as the implementation of TERM, for more people to use, like xterm.js.** 

**I hope that the opened source is to allow some people to use my code, make better tools, and avoid repeated unnecessary development, but not to gain trust and increase users.** 

For WindTerm itself, the most important thing is the features of WindTerm. WindTerm still has hundreds of features that need to be implemented, so for me, the most important thing is also to develop a better WindTerm. So I spend almost all of my time developing and fixing features. Because most people just need a good SSH terminal, not the code.

**Comment by kingToolbox** [comment]
Since this issue is neither a feature request nor a bug, it will be closed. Welcome to continue submitting new issues and feature requests. Thank you.

**Comment by shinebay** [comment]
@kingToolbox 

1. 对于第1点，对于popular SSH clients，因为其名气大，软件商不会轻易冒险去干不合法规的事，因而用户自然信任度高，这就是为什么用户敢把chrome里所有账户和密码存储到Google云端的原因。windterm目前不出名，用户的信任度不高
2. 对于第2点，据我了解，程序员基本都是去软件的官网或者GitHub的release页面下载最原生的软件，而不是去一些托管软件的第三方网站上下软件，即使putty被恶意植入后门，没有谁会去责备putty官方，而只会怪自己当初为何图省事去不知名的第三方网站下恶意软件
3. 对于第3点，对于要联网的软件，用firewall束缚这个软件难免会误伤，即使抓包到一个“uploads information to an illegal address”，保不准还有很多“illegal address”，屏蔽不完

一台服务器和一个房子一样，存储着宝贵的东西，钥匙的保管是重中之重，现在的防盗门都自带两套钥匙，一套用于装修，一套用于正式入住。房子的门都谨慎如此，何况服务器呢？

**Comment by mzky** [comment]
> @kingToolbox
> 
> 1. 对于第1点，对于popular SSH clients，因为其名气大，软件商不会轻易冒险去干不合法规的事，因而用户自然信任度高，这就是为什么用户敢把chrome里所有账户和密码存储到Google云端的原因。windterm目前不出名，用户的信任度不高
> 2. 对于第2点，据我了解，程序员基本都是去软件的官网或者GitHub的release页面下载最原生的软件，而不是去一些托管软件的第三方网站上下软件，即使putty被恶意植入后门，没有谁会去责备putty官方，而只会怪自己当初为何图省事去不知名的第三方网站下恶意软件
> 3. 对于第3点，对于要联网的软件，用firewall束缚这个软件难免会误伤，即使抓包到一个“uploads information to an illegal address”，保不准还有很多“illegal address”，屏蔽不完
> 
> 一台服务器和一个房子一样，存储着宝贵的东西，钥匙的保管是重中之重，现在的防盗门都自带两套钥匙，一套用于装修，一套用于正式入住。房子的门都谨慎如此，何况服务器呢？

Hi，我很赞同你说的前两条和最后的房子比喻，但是发现软件恶意行为对程序员来说还是比较容易的，包括使用c32asm、od、PCHunter、冰刃、MDebug等工具进行分析或反编译，很容易查找代码中的url或ip，并且不需要很强的能力；

我个人觉得用WindTerm的人中，很大一部分是有版权意识，并且不愿意购买xshell等工具的人，另一个方面是我觉得在国内，汉化软件植入广告或者恶意代码的情况比较多，所以软件提供本地化的语言和用户使用原生软件还是相对安全的。

**Comment by yilksd** [comment]
>但是发现软件恶意行为对程序员来说还是比较容易的，包括使用c32asm、od、PCHunter、冰刃、MDebug等工具进行分析或反编译，很容易查找代码中的url或ip，并且不需要很强的能力；

可能你的能力强，你周围也都是高手，但是广大群众绝大部分并没有这个能力。连做web安全的都不了解二进制逆向，更不要说普通web开发者了，对于自己不了解的领域跟小白无异。另外还有网管，也需要用到这种软件。而且软件还可以加壳混淆，这就更难了。
