### ISSUE TITLE
Can I add a shortcut button?

### ISSUE THREAD

**Issue by 107295472** [kingToolbox/WindTerm#154]
open with default editor

**Comment by kingToolbox** [comment]
Yes, you can. Almost all UI elements in WindTerm are customizable, including menus, toolbars, statusbars, strings, icons, shortcuts and so on. Please follow the steps below to add a `open with default editor` shortcut button in the `filer` pane.

- Open `WindTerm_install_path/global/wind.actions`, find `FilerPane.OpenWithDefaultEditor` and modify it:

``` json
  "FilerPane.OpenWithDefaultEditor" : {
    "text"      : "Open with default &editor",
    "icon"      : "king::editor",
    "state"     : "(action) => { let filer = window.activeKit.pane('FilerPane'); action.enabled = filer.hasSelection() }",
    "script"    : "() => { let filer = window.activeKit.pane('FilerPane'); filer.openWithDefaultEditor() }"
  },
```
Note that there are two changes compared to the original configuration, one is to add the `icon` item to set an icon. The other is to change the `action.visible` in `state` to `action.enabled`. If you don't modify it, the shortcut button will only appear when there is a selection in the `filer`, and it has no icon.
- Open `WindTerm_install_path/terminal/configs/toolbar.config`, find `"FilerPane"` and add `"FilerPane.OpenWithDefaultEditor"` to it:
``` json
  "FilerPane" : [
    { "FilterEdit" : true },
    { "Action" : "FilerPane.Cdup", "Menu": "Filer History" },
    { "Action" : "FilerPane.OpenWithDefaultEditor" },
    { "Action" : "FilerPane.Refresh" },
    { "Action" : "FilerPane.More", "Menu": "Filer More" }
  ],
```
- Restart WindTerm.

In addition, I don’t think you need to add this shortcut button, because once you set the default editor, the default editor will be used to open the file when you double-click the file.

**Comment by 107295472** [comment]
thank you
