### ISSUE TITLE
proposal about private key file

### ISSUE THREAD

**Issue by JamesRupy** [kingToolbox/WindTerm#165]
When adding a session, users can directly specify the SSH private key file in "new session" dialog box.

**Comment by kingToolbox** [comment]
Thanks for your advice. I considered providing such a design before, but then gave up. There are three reasons. 

1. It is not enough for the user to enter the private key file path, and the user name must also be entered at the same time. 
2. Not all servers are configured with public-key authentication, and whether the server supports it is only known after entering the user name when logging in. 
3. I hope that a feature has only one entry and avoid redundant designs of functions and user interfaces.

So I think the current design of placing the private key file input after the user name input is more reasonable. and may I ask if there is any inconvenience in entering the private key file during the login process?

**Comment by weihaipy** [comment]
There is no inconvenience. I also use MobaXterm and electerm,their feature are the same as I said.Maybe it will more easier to use for new users :)

**Comment by kingToolbox** [comment]
Yes, I know that. But they did not design a login wizard, so that is their only private key file input box. In the case that there is already a login wizard, it is still redundant to design a private key file input box in the session property dialog.

In addition, you may have noticed that WindTerm does not provide a user name input box in the session dialog like MobaXterm. Although the user name can be entered in the `[user@]host` format in the `host` input box, WindTerm actually discourages users from entering the user name. Because the user name is actually a very important part of the login information. When the username is known, hackers can often carry out more accurate attacks. If a preivate key file input box is provided, WindTerm must also provide a user name input box. I think this is also an insecure design. 

Through the login wizard, when automatic login is selected, the user name is also encrypted when it is saved. Therefore, the primary goal of the current design is safety, followed by convenience. Of course, I still hope to have both, so I try my best to design the interface.

**Comment by kingToolbox** [comment]
Hello, I rethinked your proposal, I think it is very meaningful, so I changed my mind :smiley: The input box `Session Setting Dialog - SSH-Authentication - Identity file for authentication` has been added to the [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version now.

You can download and try it, if there are any suggestions, please share with me, thank you very much!
