### ISSUE TITLE
[BUG] Can't disable Status Bar forever

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#174]
Hello!
When I hide status bar, it dissapears only for current instance. Maybe I can do it from config files?
Thank you!
WindTerm 2.1.0

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this issue has been fixed. You can download and check it now. Thank you.
