### ISSUE TITLE
FocusMode by default

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#175]
Is there a way to set default mode to focusMode? Normal mode will be only aviable with Ctrl+Enter then.

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this feature has been completed. Now WindTerm will enter `Focus Mode` directly after restarting. You can download and check it now. Thank you.
