### ISSUE TITLE
Lock screen disabling

### ISSUE THREAD

**Issue by SlaviusPrime** [kingToolbox/WindTerm#179]
Hello!
How I can disable a "Lock Screen"?
My comp is more security also :)

**Comment by pjgao** [comment]
Same issues! It's no need to lock screen as I always use local WSL system by WindTerm.

**Comment by izharskiy** [comment]
i did NOT set any unlock password or master password
but it locks and ask for it

using 2.1 Linux Portable

**Comment by QNoir** [comment]
had the same issue.
I found the solution [here](https://github.com/kingToolbox/WindTerm/issues/196): "If you don’t want to automatically lock the screen, you can modify global/wind.config and set application.lockScreenTimeout to 0 or a negative number (you need to restart the terminal).

**Comment by izharskiy** [comment]
> I found the solution [here](https://github.com/kingToolbox/WindTerm/issues/196): "If you don’t want to automatically lock the screen, you can modify global/wind.config and set application.lockScreenTimeout to 0 or a negative number (you need to restart the terminal).

works for me too

**Comment by kingToolbox** [comment]
Duplicate of #140 

Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

Please open the config file WindTerm_install_path/profiles/default.v10/user.config. Then add `"application.lockScreenTimeout": 0` to it to disable the lock screen.

The setting dialog is under development and will be released as part of the WindTerm_2.2.0 release. I believe it will be much easier to modify the parameters at that time.

**Comment by kingToolbox** [comment]
Hello, I am happy to inform that the development of the `settings` dialog box has been completed. Now not only can disable `Lock Screen` very conveniently, `Menubar - Session - Preperences - Settings - Security - Lock screen timeout`, but also can easily modify any configuration. Please download and check the new [WindTerm_2.2.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease), thank you.
