### ISSUE TITLE
Greate Work! I will use it to instead Xshell and Xftp!

### ISSUE THREAD

**Issue by shiqianwei0508** [kingToolbox/WindTerm#182]

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am glad you like WindTerm. The latest [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released, welcome to update and use. Thank you very much.
