### ISSUE TITLE
Set mouse scroll speed

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#183]
WindTerm 2.1.0
Hello!
Is there any way to set mouse scroll speed? I.e. not 1 line per click, but 2 lines (or more).
TY!

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this feature has been completed. You only need to set the number of scrolling lines you want through the setting `Session Settings Dialog - Window - Roll the mouse wheel to scroll`. 

You can download and check it now. Thank you.
