### ISSUE TITLE
How do I close an automatic session?

### ISSUE THREAD

**Issue by helloxz** [kingToolbox/WindTerm#184]
The last session will be opened automatically when windterm is opened next time. How to make windterm not open the last session automatically? Thank you.

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

When the pop-up box asks
```
One or more sessions are opening, Do you want to restore these sessions at the next startup?
```
when exiting, select `No` to avoid restoring the previous sessions when the next startup. An easier-to-use setting interface will be provided in the next prerelease version. If there is any progress, I will update here, thank you.

**Comment by helloxz** [comment]
正在使用发音
I accidentally permanently closed the session confirmation button. How can I turn it on again?
在 2021年9月27日 +0800 07:56，kingToolbox ***@***.***>，写道：

**Comment by kingToolbox** [comment]
Please open `WindTerm_install_path/default.v10/user.config` and remove the lines:

>   "terminal.askBeforeCloseWindow" : false,
>   "terminal.restoreLastViews" : false,

Then the pop-up box will show again.

**Comment by helloxz** [comment]
It has been resolved temporarily. Thank you for your guidance.
