### ISSUE TITLE
Can add the automatic copy function of selected text? thanks

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#19]
Can add the automatic copy function of selected text? thanks

**Comment by kingToolbox** [comment]
Do you mean copy to clipboard on selection? Ok, I will add this function in the next version, thank you.

**Comment by kingToolbox** [comment]
**Select-to-copy** and **middle-click-to-paste** has been added in the version [1.8 prerelease 1](https://github.com/kingToolbox/WindTerm/releases/tag/1.8), please download and check, thank you.

Please note that **Select-to-copy** is disabled by default on Windows to prevent accidentally overwriting the content on the clipboard, because Windows does not has the concept of a separate selection and clipboard like the X11. You should set the option **_text.autoCopySelection_** in **_WindTerm-Install-Path/global/wind.config_** to **true** to enable it.

**Comment by kingToolbox** [comment]
For most usage scenarios, you can drag and drop the selection to input it. I think this is faster than select-to-copy then middle-click-to-paste, especially without the side effects of overwriting the clipboard.

You can watch the video [Tips / Input By Dragging And Dropping Text](https://kingtoolbox.github.io/2020/06/20/tips-input-by-dragging-and-dropping-text/) to learn more. I'm sure you will like it after you try it.

**Comment by xzhuiz** [comment]
Yeah, it's really good, thank you very much.
By the way, the function drag and drop the selection you mentioned does not work in my environment. When I drag the selection, nothing changes except the mouse movement

**Comment by kingToolbox** [comment]
Just click the left button on the selection and drag it to offset a certain distance and release it. Not drag it all the time, you need to drop it. You can watch the video mentioned above and try again.

**Comment by xzhuiz** [comment]
yes, what I did was the same as what you said and the video. Dragging from chrome to WindTerm works, but not work inside WindTerm. dargging from WindTerm to others not work too.
Maybe my WindTerm configuration prohibits drag the selection?

**Comment by kingToolbox** [comment]
No, there is no option to prohibit this and it should always work.

Would you like to open cmd or powershell and try again? Please pay attention to three points. First, please confirm that "Copy And Paste" on selection is working properly. The second is that the text will be entered at the current command prompt position instead of where the mouse is released. The third is the cursor should not be a prohibited icon when releasing.

**Comment by xzhuiz** [comment]
does not work in cmd and powershell too.
Alt+c Alt+v Alt+x and Select-to-copy work very well.
My problem is that the cursor does not change from the pointer to the forbidden icon when dragging selected

**Comment by kingToolbox** [comment]
Thank you very much! This is really very strange, I have never seen it before and I need some time to think about it. If you have another computer, maybe you can try this on it.

In addition, this is currently only an internal function. Only limited support for some other programs. For example, although you cannot drag and drop it into the chrome's address bar, you can drag and drop selected text from WindTerm into the github's comment box.

This will be improved in the **version 1.8 prerelease 2** to facilitate drag and drop any selection to other programs. Maybe after finishing, we can see if your drag and drop can work. Please keep follow and thanks again.

**Comment by kingToolbox** [comment]
I forgot to say that the new version 1.8 prerelease 2 will be released tomorrow or the day after tomorrow, so there is no need to wait too long :relaxed:

**Comment by xzhuiz** [comment]
My other windows7 can indeed work. it's my fault...
Don't worry about this too much. Select-to-copy is very good enough for me. Thanks again.

**Comment by kingToolbox** [comment]
Ok, the new version [1.8 prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/1.8) has been released as promised. You can drag and drop any selection to the sender, addressbar and some other applications now. Please download and check, thank you.

Btw, It's nice to hear that WindTerm works well on other computers. And if there are no other problems, this issue will be closed :smile: You are always welcome to submit new feature requests and issues.

**Comment by xzhuiz** [comment]
1.8 prerelease2 can't drag too. It should be related to my windows environment.
Please close this, thanks again.

**Comment by emoxam** [comment]
text.autoCopySelection = false
is seted up on ubuntu too, i changed it to true but still the copy pastes only in windterm, i cant's paste to the OS.
