### ISSUE TITLE
the 2 issues for "Rename Group" name in "Quick Commands" window

### ISSUE THREAD

**Issue by yaray** [kingToolbox/WindTerm#191]
Two issues:
"Rename  Group" name in "Quick Commands" window, (Issue 1) the title is 'Add Group', and click the 'Cancel' button or close the dialog window, then (Issue 2) the group name is blank in the 'Group Name' List.

WindTerm Version: 2.1.0

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and the issue 2 has been fixed. You can download and check it now. And the issue 1 will be fixed in the next prerelease version, thank you very much!

**Comment by yaray** [comment]
Wish you have a perfect trip :-)

updated to WindTerm_2.2.0_Prerelease_1, I confirmed the issue 2 has been fixed, Thank you!

**Comment by kingToolbox** [comment]
It is indeed a good trip, thank you for your blessings. :smile:

The first issue has also been fixed and will be released in the next prerelease version. It was just missed last time.

**Comment by kingToolbox** [comment]
I am glad that the first problem has also been fixed, please download [WindTerm_2.2.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) and check it, thank you very much.

**Comment by yaray** [comment]
upgraded to WindTerm_2.2.0_Prerelease_2, I confirmed the issue 1 has been fixed. Thank you very much!
