### ISSUE TITLE
The chinese words are messy codes in the log-file when turn on  logging in the "Session Property" setting window

### ISSUE THREAD

**Issue by yaray** [kingToolbox/WindTerm#192]
The chinese words are messy codes in the log-file when turn on  logging in the "Session Property" setting window.

The chinese words are correct codes in the console output.
The chinese words are messy codes in the log-file.
The log-file's code is ANSI, When convert to UTF-8, the chinese words are messy codes in the log-file, too.
So I guess the messy codes have been generated before write-into the log file.

---------
The part-informations of "Session Property" setting window:
Session: Charset: UTF-8
Terminal --> Logging: 
                                    Log Types: Log printable output
                                    Log Options: Append log file
---------
Environment:
WindTerm 2.1.0 portable
OS: Windows 7 旗舰版  with Service Pack 1

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

If the `Session Charset` is set to `UTF-8` and the console output is OK, then the log will also be recorded in `UTF-8` instead of `ANSI`. So can you use a text editor that can detect encoding to try to open it again?

If possible, you can also post the log and the corresponding text on the screen as attachments here. In this way, I can also help analyze and see what the problem is. Thank you.

**Comment by yaray** [comment]
Very sorry! Suddenly, I found the issue is notepad++'s bug:
use Windows's Notepad to open the log file, the chinses words are correct codes.
but use notepad++(v5.7.6) to open the log file, the chinese words are messy codes.

**Comment by kingToolbox** [comment]
It's okay, welcome to continue submitting issues and feature requests. :smile:
