### ISSUE TITLE
Is there a way to start up with focus mode?

### ISSUE THREAD

**Issue by in-out** [kingToolbox/WindTerm#197]
I wanna start windterm with focus mode.
but i can't find config about it.

**Comment by kingToolbox** [comment]
Duplicate of #175 

Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this feature has been completed. If you were in `Focus Mode` before exiting last time, you will also enter `Focus Mode` directly after restarting. This does not require any settings. You can download and check it now. Thank you.

**Comment by in-out** [comment]
> Duplicate of #175
> 
> Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time.
> 
> I am happy to inform you that [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this feature has been completed. If you were in `Focus Mode` before exiting last time, you will also enter `Focus Mode` directly after restarting. This does not require any settings. You can download and check it now. Thank you.

thanks , it works
