### ISSUE TITLE
In the 2.6.0, login message in the bastion machine reads "Channel request exec failed", but the connection is actually working.

### ISSUE THREAD

**Issue by capricornxl** [kingToolbox/WindTerm#1983]
See the picture below:    
![image](https://github.com/kingToolbox/WindTerm/assets/40738379/cf674d0f-ab31-4e17-a45d-59bf32f03a24)

However, in 2.5.X, the above problem does not exist.    
I tried to enable the debug of WindTerm, but the log is empty.

I wonder if there were any changes made in 2.6.0 that caused this error?    
Doesn't anyone else have this problem?

**Comment by kingToolbox** [comment]
This is may caused by `Sysmon`, please download and use version [WindTerm_2.6.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease), and disable `Sysmon` in the `session settings dialog`.

![image](https://github.com/kingToolbox/WindTerm/assets/51009775/8c741102-77ff-4f95-b611-a55628f16cf4)
