### ISSUE TITLE
The terminal garbled after I access the garbled file such as `cat` command

### ISSUE THREAD

**Issue by hongweipeng** [kingToolbox/WindTerm#199]
![图片](https://user-images.githubusercontent.com/7546325/133878382-16208dbc-a74a-4e1c-a104-e20e2a0e94d4.png)

**Comment by lyx582** [comment]
我同样遇到了这个问题，我用histoty 命令后也是这样乱码，应该是查看的文件有特殊字符导致程序崩溃

**Comment by kingToolbox** [comment]
Dulicate of #162

Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

Strictly speaking, this is not an error, because terminals is not suitable for printing binary data or files. You can read a more detailed explanation [here](https://github.com/kingToolbox/WindTerm/issues/162#issuecomment-900134015). 

In order to solve this problem, the newly released [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has added the `Reset Character Set feature`. If you encounter this problem again, you only need to simply execute the `Right click menu - Reset - Reset Character Set` menu item to restore the normal display. You can download and use it. Thank you.

**Comment by hongweipeng** [comment]
I tried, no problem.
