### ISSUE TITLE
2个月没更新了，项目是不是凉了？

### ISSUE THREAD

**Issue by EverythingGoesWithTheFlow** [kingToolbox/WindTerm#201]
看介绍说预计8月中旬更新2.2版本的 这都9月下旬了，这是凉了么？

**Comment by yang-kai-shuo** [comment]
我每天也来刷下，也没看到作者有回复消息。不知道不是作者有啥事。

**Comment by gooker** [comment]
已经2年了,不至于,不过最近作者确实没出现了.

**Comment by lyx582** [comment]
软件还是很好用，希望作者可以持续更新

**Comment by pdckxd** [comment]
要是能完全开源就好了，一些问题大家都能帮着处理一下

**Comment by OIdDriver** [comment]
刚入坑难道就要凉？？

**Comment by l-we** [comment]
我正在考虑入不入坑呢，等2.3发布在决定吧

**Comment by gooker** [comment]
> 我正在考虑入不入坑呢，等2.3发布在决定吧

除了连接管理没有xshell方便,基本上完全替代了 xshell.

**Comment by leesings** [comment]
每天一刷，好软件值得等待

**Comment by helloxz** [comment]
@pdckxd @gooker @OIdDriver @l-we @leesings 

我也是每天一刷，刚刚看到作者开始回复issues，作者刚刚长途旅行回来。

> Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time.

2.2.0的预览版出来了，可以去下载了：[https://github.com/kingToolbox/WindTerm/releases](https://github.com/kingToolbox/WindTerm/releases)

**Comment by EverythingGoesWithTheFlow** [comment]
> @pdckxd @gooker @OIdDriver @l-we @leesings
> 
> 我也是每天一刷，刚刚看到作者开始回复issues，作者刚刚长途旅行回来。
> 
> > Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time.
> 
> 2.2.0的预览版出来了，可以去下载了：https://github.com/kingToolbox/WindTerm/releases

看预告2.2.0会出多语言界面 期待中

**Comment by kingToolbox** [comment]
Thank you all for your support of WindTerm. I am also sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issues in time. 

Another reason for the delay in releasing a new version is that this version has changed a lot. The statistics given by Git since the previous version on July 17th are as follows:

> **Lines: 14915(+) 7403(-) Files: Modified = 104 Added = 35**

I have to say that the workload is huge, nearly 400 lines of code are modified or written every day. It took more than a week to even just retest all the functions. This is mainly because the old framework cannot implement the `SSH ControlMaster` feature well. So I redesigned, rewritten, and refactored a lot of core network code. This is something I could not estimate when I made the road map. But fortunately, I always habitually add `for reference only` to the road map. :smile: @EverythingGoesWithTheFlow 

For now, this project is still far from over. From the beginning, there is a long-term plan for the development of WindTerm:

Version | Level | Target | Status
------------ | ------------- | -------------- | ----------
v0.x | Basic | Basic framework and basic features, and be able to use them normally | Finished
v1.x | Manual | Perfect features and can be used by most developers in their daily work | Finished
v2.x | Semi automatic | Through triggers, macros, events, notifications and so on, developers can be assisted to complete some operations. | Developing
v3.x | Fully automatic | Through plugins, scripts, machine learning and so on, automatically operating with achieving non-attended | Planning

I expect to complete v2.x in the first half of 2022 and v3.x in 2023. The development of WindTerm is inseparable from your support. Let us move on. 

@yang-kai-shuo
You guessed it, I went on a long trip :laughing: 

@gooker 
Thank you for your continued support and trust. If you allow, I would like to ask you why XShell's connection management is better. I think I can learn from it and continue to improve WindTerm.

@lyx582 
Thank you, I will.

@pdckxd 
I think the tools made by one person will be more consistent in style and design. More importantly, as a partial open source project, WindTerm actually protects the data security of every user. So far, no one needs to worry about downloading a backdoor or malicious code injected version like Putty. 

Of course, everything has both good and bad sides. But I am very satisfied with the current state of WindTerm. I think I have the ability to solve almost all problems and have great enthusiasm to complete this project.

**Comment by pdckxd** [comment]
>> Of course, everything has both good and bad sides. But I am very satisfied with the current state of WindTerm. I think I have the ability to solve almost all problems and have great enthusiasm to complete this project.
Good to hear. Thanks to invent this awesome project. By the way, is there a plan to support Apple M1 natively?

**Comment by kingToolbox** [comment]
@pdckxd 
Yes, there will be M1 version. But the release time is not up to me. First, I need to wait for `Qt` to release `Qt 6.2.0` or `Qt 6.2.1`. The second and more important thing is that `Apple` needs to release the new `M1X macbook pro` in October or November. 

In addition, since the current Mac version of WindTerm is still very unstable, I need to improve the Mac version first.

**Comment by kingToolbox** [comment]
@gooker 
Thank you for your illustrated description.

One of the design principles of WindTerm is to pop up as few dialog boxes as possible. So the first advantage of XShell is probably difficult to learn from. But there is no problem with the second advantage, which can be realized after WindTerm use [Qt-Advanced-Docking-System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System).

Although `Tab View` cannot be dragged at present, you can easily move `Tab View` to the specified `Tab Group` by using the `move to group` function. You can read [UI / Tab](https://kingtoolbox.github.io/2021/06/28/ui_tab/) to learn more.

**Comment by gooker** [comment]
> [Qt-Advanced-Docking-System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System).
> 
Hope use it soon,and Recommended this qt dock to my qt group colleagues .😄

**Comment by jxhui23** [comment]
最近还有更新吗
