### ISSUE TITLE
Report the zh-CN(Simplified Chinese) translation file here, for version 2.6.0/简体中文翻译文件(2.6.0)分享

### ISSUE THREAD

**Issue by hityb** [kingToolbox/WindTerm#2062]
Based on version 2.6.0, I have improved the translation file for Simplified Chinese and would like to share it with everyone here. I also hope the author (@kingToolbox ) can package the files into the release package.
---
基于2.6.0版本，我完善了一下简体中文的翻译文件，在这里分享给大家。同时希望作者把文件打包到分发包中。
---
[zh-CN.locale.zip](https://github.com/kingToolbox/WindTerm/files/13885656/zh-CN.locale.zip)

**Comment by kingToolbox** [comment]
Thank you very much for your hard work, it's been great. Due to the ongoing development of version `2.6.0`, I haven't had time to extract the latest translation files. The delay in completing version `2.6.0` has put a lot of pressure on me, so I haven't been able to focus on other things, including issues, change logs. Fortunately, the work is almost finished, so hopefully I can release it soon.

**Comment by springsunx** [comment]
I have extracted the latest English strings as much as possible and translated them.
[zh-CN.zip](https://github.com/kingToolbox/WindTerm/files/13944766/zh-CN.zip)
![image](https://github.com/kingToolbox/WindTerm/assets/23657968/56785948-39b5-4062-88c7-76ddeb7a7ae2)
![image](https://github.com/kingToolbox/WindTerm/assets/23657968/7fab2b85-1632-4edb-b345-5f3ab5d901ff)
