### ISSUE TITLE
[feature] SFTP SSH controlmaster integration

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#209]
Hello!
Since WindTerm will support controlmaster's shared session, is it possible to implement such feature as:
- you log in remote server master01 -> SFTP pane shows master01
- you ssh from master01 to master02 -> SFTP pane shows master02
If it's real, it would be killer-feature. With agent forwarding, maybe? Does ssh server have to support controlmaster?
Thank you!

**Comment by kingToolbox** [comment]
`SSH MasterControl` has been supported in `version 2.2.0_Prerelease_1`, but I am afraid the feature you mentioned can not be implemented. Because when you connect to `master02` via command `ssh` in `master01`, the connection is taken over by `OpenSSH`, so WindTerm can't do anything. 

Your needs can be achieved through `Jump Servers`. You only need to set `master01` to a `JumpServer` of `master02`. Then after `master02` is successfully connected, `master02` is displayed in the `Filer` panel. You can read [Jump Server](https://kingtoolbox.github.io/2021/03/11/proxy-jump-server/) to learn more.

The SSH server does not need to support `ControlMaster`. This is entirely a feature of the SSH client. However, the server configuration `MasStartups` and `MaxSessions` will affect how many sessions can be successfully duplicated.

**Comment by eugenov** [comment]
Thank you for clarification. You do a great job!

**Comment by eugenov** [comment]
Pity, I have 1K+ servers, so creating 1K+ sessions won't fit. So `Jump Servers` thing is not for me...

**Comment by kingToolbox** [comment]
Don't worry. What I am talking about is that a single connection can only support `MaxStartups` or `MaxSessions` sessions. But if each of your connections is newly created, you are not subject to this restriction. Besides, the values of `MaxStartups` and `MaxSessions` can also be set. You can set it to `2000` to avoid the restriction.
