### ISSUE TITLE
[feature request] Include IP in log file's name

### ISSUE THREAD

**Issue by yilksd** [kingToolbox/WindTerm#227]
Now windterm can include date, time, tab title, etc.  in the logfile's default name, but it still cannot include the IP of the ssh remote host. Could you add this feature?

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.2.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been released and this feature has been added, please download and check, thank you.

BTW:
When you choose to record all session output, the log file must be created before the connection in order to record the entire connection process. At this time, because the host address cannot be obtained because the connection is not yet connected, the `%h` will be replaced with `UnknownIP` in the log file name. But when the session is closed, `UnknownIP` will be automatically replaced with the correct IP address.
