### ISSUE TITLE
Linux release?

### ISSUE THREAD

**Issue by Twink-Polar** [kingToolbox/WindTerm#24]
This project looks amazing! I'd really like to take a look at the Linux version. Are you still planning on a late November release?

**Comment by kingToolbox** [comment]
Yes, I am still working very hard so that I can release the Linux version in the remaining days as I promised. Since it is the first Linux version, there is a lot of work to be done. But the very good news is that the prelease of the Linux version has been completed and is being tested on multiple Linux distributions, including Ubuntu 18.04 LTS, Ubuntu 20.04 LTS, Debian 10, CentOS 7 and so on.

The remaining work includes automatic detection of system shells, testing SSH functions, redesigning shortcut keys and so on. There are also some native codes that need to be implemented.

I hope there will be a good tool for you to use when it is released at the end of the month, please keep attation and thanks for your recognition.

**Comment by Twink-Polar** [comment]
Thank you for the response. Completely understand this will be the first Linux version. Looking forward to testing it out.

**Comment by kingToolbox** [comment]
Sorry for late response. The workload of the Linux version is more than I estimated. I have been working hard these days and finally released a new Linux prerelease version just now.

The SSH function works well except for x11 forwarding and agent forwarding. But unfortunately, there are still some bugs, especially in the Linux shells, e.g. bash or zsh. The most important bug is the inability to use vi correctly. and some shortcut key settings also need to be changed, otherwise it will conflict with Emacs.

I will continue to solve the above problems and will release an updated version as soon as possible. If you encounter problems, please submit new issues, thank you in advance.

**Comment by Twink-Polar** [comment]
I look forward to testing it. Thanks for the update.

**Comment by kingToolbox** [comment]
I did a simple performance test. On a centos 7 vm (cpu: 4 cores, memory: 4Gb), execute "time seq 1 10000000":
|  | real | user | sys |
| --- | :--: | :--: | :--: | 
| Gnome Terminal | 13.417s | 0.175s | 3.690s |
| WindTerm (bash, No color scheme) | 6.599s | 0.159s | 3.664s |
| WindTerm (bash, Use color scheme) | 7.686s | 0.128s | 3.736s |
| WindTerm (SSH localhost, Use color scheme) | 6.798s | 0.159s | 3.964s |
| WindTerm (SSH localhost, Use color scheme) | **6.237s** | 0.167s | 3.773s |

The performance seems to be good. :smiley:

**Comment by Twink-Polar** [comment]
Downloaded and had quick test run. Very impressive and configurable tool. Finding my feet with it. 

Have you thought about how the tool could work with existing ssh configs?

**Comment by kingToolbox** [comment]
Do you mean automatic import existing ssh configs as sessions? Very good idea, WindTerm can already import the putty and shell sessions automatically, and use the existing ssh known hosts configuration.

I will try to import the ssh configuration further. Thank you!

**Comment by kingToolbox** [comment]
The existing ssh configs can be automatic imported as sessions now. Currently only supports importing Host, HostName and Port. Any wildcards, placeholder characters and other options are not supported. I think this is enough, if there are other needs, please let me know.

The new version 1.9 has been released, please download and check, thank you.

**Comment by Twink-Polar** [comment]
That's great thank you! I'll download and take it for a spin.

**Comment by kingToolbox** [comment]
Hope to satisfy you. If there are no problems, this issue will be closed.

**Comment by kingToolbox** [comment]
If there are other feature requests, please create a new issue, thank you.
