### ISSUE TITLE
don't support new line mode config

### ISSUE THREAD

**Issue by dbitc** [kingToolbox/WindTerm#263]
normal:
new line mode:
CR  or
LF   or
CR + LF or
AUTO

eg:
![AAA_16370616689610](https://user-images.githubusercontent.com/30992330/141976919-b4806436-2aa8-42d6-91f9-2ad631bc8faf.png)

**Comment by dbitc** [comment]
Duplicate of #

**Comment by dbitc** [comment]
error log:
SDK.0> 
       SDK.0> 
              SDK.0> 
                     SDK.0> 
                            SDK.0> 
                                   SDK.0> 
                                          SDK.0> 
                                                 SDK.0> 
                                                        SDK.0> 
                                                               SDK.0> 
                                                                      SDK.0> 
                                                                             SDK.0> exit
                                                                                        SDK.0>

**Comment by kingToolbox** [comment]
`WindTerm` does support the `New line mode`. The reason why the text cannot be aligned is because the server did not send  control sequences of `New line mode` correctly. You can read [this comment](https://github.com/kingToolbox/WindTerm/issues/134#issuecomment-888111672) for a more detailed explanation.

In subsequent versions, perhaps version `2.3.0` or `2.4.0` an interface will be provided to allow you to set the initial value of `New line mode` to avoid this problem. Please stay tuned, thank you.

**Comment by dbitc** [comment]
[WindTerm_2.3.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) has been released and this issue has been fixed
