### ISSUE TITLE
log bug-right button log don't sync with real log cfg.

### ISSUE THREAD

**Issue by dbitc** [kingToolbox/WindTerm#266]
log bug- righ button menu don't sync with real log cfg.
1. cfg log
![image](https://user-images.githubusercontent.com/30992330/141943093-5f8e1895-4178-4760-b622-2bb29e2fe69c.png)
but right button menu not same with cfg log. now is start, dont be running.
![WXWorkCapture_16370491453660](https://user-images.githubusercontent.com/30992330/141943315-f0fa1120-654c-432e-97ab-0925d7732082.png)

**Comment by kingToolbox** [comment]
These are two independent features and therefore have their own independent settings. 

The reason for this design is to prevent read and write conflicts between the `session log` and the `manual log`. When the user specifies **a fixed log name** instead of **a log name that uses the template**, there will be a conflict.
