### ISSUE TITLE
2.2.0 prerelease5 word wrap，it  looks strange

### ISSUE THREAD

**Issue by leesings** [kingToolbox/WindTerm#270]
![image](https://user-images.githubusercontent.com/43227866/142339625-bf598fbb-eee1-42b9-90e3-1a00342645cb.png)

![image](https://user-images.githubusercontent.com/43227866/142340171-83bbe926-409e-401d-8bea-362581125500.png)

**Comment by leesings** [comment]
Turn off automatic line wrapping, and sometimes it’s still displayed in line wrapping

**Comment by kingToolbox** [comment]
From the screenshot, I think it has nothing to do with the `Wrap Mode` of `WindTerm`. If each text line is wrapped by `WindTerm`, a blue wrap symbol will be displayed at the end of the line. 

I guess the reason is that the line is too long. You can try to set `Session Settings - Window - Columns` to a larger value, such as `999` and uncheck `Session Settings - Window - Adjust the window rows and columns`, and see if it won’t wrap.

**Comment by leesings** [comment]
![image](https://user-images.githubusercontent.com/43227866/142533588-172ccb98-6aec-41d5-aec0-a44c5d0c1eb9.png)

When I input the same command twice, the display effect is different. The first time it looks normal and there is no line feed. The second time part of the content becomes line feed. I'm sure the contents of the two commands are the same

**Comment by kingToolbox** [comment]
Did you turn on the `Menubar - View - Symbols - Line Endings`? Otherwise, `LF` may appear only when the received text is parsed incorrectly. But from your screenshots, there should be no such errors. 

However, the output of the same command executed twice should usually be the same, which may be an error. Can you collect the debug log for me for further analysis, if possible, the steps are as follows:

- Open your session.
- Check the menu item `Menubar - Mode (7) - Debug Mode` before you excute `docker ps -a`.
- Excute `docker ps -a` twice, and make sure that the two outputs are different as in the screenshot. 
- Uncheck the menu item `Menubar - Mode (7) - Debug Mode`.
- Click the menu item `Right click menu - Log - Open Log Folder`.
- Open the folder debug and paste your log file in your comment here. You can zip it before upload.

The log content is in plain text and will not contain any private information. You can use any editor to view it. Thank you.

**Comment by leesings** [comment]
[2021-11-20_11.30.20.log](https://github.com/kingToolbox/WindTerm/files/7573859/2021-11-20_11.30.20.log)

![image](https://user-images.githubusercontent.com/43227866/142713152-116fe515-c11c-429a-aebf-5a248ba2134f.png)

The result of the first command is partially wrapped, and the result of the second command is displayed in a newlin
[result.txt](https://github.com/kingToolbox/WindTerm/files/7573863/result.txt)
e.

**Comment by kingToolbox** [comment]
The `log` and `result.txt` you provided played a very important role in solving this issue. Now I am happy to inform you that [WindTerm_2.2.1](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

**Comment by kingToolbox** [comment]
The `log` and `result.txt` you provided played a very important role in solving this issue. Now I am happy to inform you that [WindTerm_2.2.1](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

**Comment by leesings** [comment]
The line feed problem of the same command result is OK now. I found a new problem. When I enter docker ps -a, and then continue to press enter, my video recording effect will appear in the above historical content

https://user-images.githubusercontent.com/43227866/143533807-226bb7f4-45cf-4474-8023-9babd2706ccb.mp4

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.2.2](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

**Comment by leesings** [comment]
excellent!
