### ISSUE TITLE
Multiple monitors composition problem & a file transfer ETA display error.

### ISSUE THREAD

**Issue by funkpopo** [kingToolbox/WindTerm#273]
Just woke up and found out that v2.2.0 has been published! Great work!

I have tested a few features that I didn't use frequently before. And found that in a multi-screen environment, customizing the font size (not following the theme setting) will cause the string in the command line to be misaligned, especially when the resolution of multiple screens is different/the same resolution but different sizes, The probability of this happening is greater.
The following is the environment where I found the problem:
1. Notebook (1920 * 1080)  zoom scale: 125%
![image](https://user-images.githubusercontent.com/75678670/142551530-73fa4920-05b5-4a84-8d53-2f4e1f19e88d.png)
2. External screen (1920 * 1080)
![image](https://user-images.githubusercontent.com/75678670/142551583-8868986e-132d-4c38-a0a3-8cadcd90bbf2.png)

Suggested solution:
1. Try Qt6.
2. Disable the font size option and only give users the option to change the font style.

The second is the ETA information displayed at the bottom of the window during file transfer. The ETA info will not be automatically refreshed when the mouse pointer is moved to the top of the transferred file. However, the ETA info is complete and accurate when  select "Show all".

Suggested solution:
1. Display the abbreviated transmission overview column completely, and disable floating notifications.
2. Check if there is a problem with the hook of the mouse event.

**Comment by kingToolbox** [comment]
Thank you for your great suggestions. Since I don't have multiple screens, there may be problems with support for multiple screens. Currently, I am also waiting for the release of `Qt 6.2.2` and will upgrade to this version after its release. I hope that the support for multiple screens can be improved.

For the second question, due to the design of `QTooltip`, the displayed text content is indeed static. This is why the circular progress bar is designed. Usually the transmission time is not long, and the circular progress bar is enough for users to see the current progress. Displaying dynamic content will increase the complexity of the implementation. What do you think about this?

**Comment by funkpopo** [comment]
> Thank you for your great suggestions. Since I don't have multiple screens, there may be problems with support for multiple screens. Currently, I am also waiting for the release of `Qt 6.2.2` and will upgrade to this version after its release. I hope that the support for multiple screens can be improved.
> 
> For the second question, due to the design of `QTooltip`, the displayed text content is indeed static. This is why the circular progress bar is designed. Usually the transmission time is not long, and the circular progress bar is enough for users to see the current progress. Displaying dynamic content will increase the complexity of the implementation. What do you think about this? 

Sorry for the late reply.
Since the display of dynamic transfer information already have a small tab info and progress bar, I think maybe it is not necessary for additional content to exist. Remove this mouse event maybe a well solution.
Thanks again for your great work! It is my honor to give any suggestions!

**Comment by kingToolbox** [comment]
Although there are buttons that display part of the information, it is actually incomplete, while `QTooltip` can display complete information, such as `Target Directory`, `Time elapsed`, `Average speed`, etc. which is still very useful for users. In addition, the bottom space is limited, after downloading too many times, the buttons will be squeezed because of too many, making the text almost impossible to display. `QTooltip` will be very useful at this time. And it is also a good design habit to add appropriate `QTooltip` to the `Widgets`.

So I think it would be a better choice to keep `QTooltip`. What's more, there are almost no side effects for users to use. :smile:

**Comment by funkpopo** [comment]
> Although there are buttons that display part of the information, it is incomplete, while `QTooltip` can display complete information, such as `Target Directory`, `Time elapsed`, `Average speed`, etc. which is still very useful for users. In addition, the bottom space is limited, after downloading too many times, the buttons will be squeezed because of too many, making the text almost impossible to display. `QTooltip` will be very useful at this time. And it is also a good design habit to add appropriate `QTooltip` to the `Widgets`.
> 
> So I think it would be a better choice to keep `QTooltip`. What's more, there are almost no side effects for users to use. 😄

Since it may be a useful function in the future, I also agree with remaining the `QTooltip`, guessing it will become a brief and useful tip window. Glad that we can discuss this, thank you for your patience!

**Comment by kingToolbox** [comment]
I am also very happy to discuss and reach an agreement with you. However, this issue contains two questions, and the rest `Multiple Screens` will have to wait until the end of the month to get results. :smile:
