### ISSUE TITLE
windows下密码输入错误会卡很长时间。

### ISSUE THREAD

**Issue by ssmmtt** [kingToolbox/WindTerm#276]
windows下密码输入错误会卡很长时间。

**Comment by kingToolbox** [comment]
How long do you have to wait each time? Usually several seconds or tens of seconds are normal. `WindTerm` uses the `PBKDF2` algorithm, which makes it necessary to perform a lot of calculations every time the master password is verified to avoid being brute force cracked locally.

Depending on the performance of your machine, each calculation usually takes a few seconds, so that no more than 80,000 password combinations can be tried every day, which greatly reduces the possibility of brute force cracking.

**Comment by funkpopo** [comment]
在保证本地环境较为安全的前提下可以优先考虑使用弱密码。这将在一定程度上相对减少密码校验的时间。
The use of weak passwords can be a priority while keeping the local environment secure. This will reduce the time for password validation to some extent.

**Comment by ssmmtt** [comment]
![动画](https://user-images.githubusercontent.com/16244320/142760214-e4ac48d4-3bab-4128-9fd4-8718bb483339.gif)

**Comment by gooker** [comment]
I have a similar situation. I modify the virtual machine IP, then modify the IP in the window , press enter, enter the user name, and then enter the password. It will be stuck for a long time

**Comment by funkpopo** [comment]
@kingToolbox 
Have just re-checked this problem.
When I tried to create a new session, the default connection has been set as "ssh: notty", as shown in the image down below. I just created a virtual machine then login with the local platform and used the newest version of WindTerm.
![image](https://user-images.githubusercontent.com/75678670/142790857-22f67a72-4713-43aa-ad9f-1d5edfc8bd60.png)

Regarding the above bug, after repeated testing, it was confirmed that the newly created session would be stuck after entering the password and clicking "Confirm". After clicking "Cancel", an authentication error and a new password window will pop up, and the connection cannot be successfully established at this link. Shown as the result down below.
![image](https://user-images.githubusercontent.com/75678670/142791553-e7295346-c570-4f59-a2e0-67939206c2cc.png)

By the way, every session that has been created successfully before the new version v2.2.0 was released can be used with no problem. And the session info which was saved into the /profiles/../terminal/user.sessions is different from the old session infos. I will paste a sample here. The "Euler OS" is a CentOS-based version of Linux.
![image](https://user-images.githubusercontent.com/75678670/142792229-dd207afb-5dad-4e21-8b60-d4a9c415f7f7.png)

Possible sources of the problem:
1. You may accidentally change the default settings of creating a new session with the unavailable "ssh:notty" that caused the establishment failure.
2. May exist some default session conflicts of the new version ( v2.2.0) with old versions.
3. There may be some undiscovered possible causes I have not found out yet...

**Comment by kingToolbox** [comment]
Sorry, I thought it was `master password` before, but when I saw the screenshot, I realized that it was the `SSH session` password.

It should be noted that after clicking `Continue` in the login wizard, `WindTerm` **was not actually stuck**, but is waiting for the server to return the login result. At this time, you can still change your password and click `Continue` again. If the password is correct, the login will be successful immediately.

In order to avoid this misunderstanding, I will add some tips after clicking `Continue`.

BTW:
When the login fails, `WindTerm_2.2.0` will try to automatically log in three more times, with an interval of 500 millisecond between each login. This design is to avoid as much as possible the login failure caused by accidental network interruption. But apart from this, there is no additional overhead. All waiting time depends entirely on the processing time of the network and server.

**Comment by kingToolbox** [comment]
@funkpopo 
Thank you for doing such a detailed test and giving a proper analysis.

**Comment by ssmmtt** [comment]
> 

恩  最好是提示一下鉴权失败。

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.2.1](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, now when the login fails, an error message will be displayed in time, please download and check it, thank you.

**Comment by ssmmtt** [comment]
niec,It works !
![image](https://user-images.githubusercontent.com/16244320/143388240-85394272-45fd-4c48-9f60-285266992dea.png)

**Comment by kingToolbox** [comment]
Okey, this issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
