### ISSUE TITLE
Not work create directory via dot.

### ISSUE THREAD

**Issue by karagi4** [kingToolbox/WindTerm#283]
This very sadly.  I have many catalogs for connections, which now not view how nested.  Now in connections chaos. :(
What me do?

**Comment by funkpopo** [comment]
Since you finished creating a directory with a name that contains ".", if you want to check via "Filer", you can click additional settings besides the "refresh button", then click "show hidden items" down below. I think you may successfully see the hidden "dot files".
![image](https://user-images.githubusercontent.com/75678670/142822028-0e619168-7eab-48a7-816b-ef5179f0a5fb.png)

If you use WindTerm to connect your Linux OS, use `ls -a` to view all files including hidden files.
![image](https://user-images.githubusercontent.com/75678670/142822055-5de4a358-fe8b-4095-b16d-dc2eaa56bc13.png)

**Comment by kingToolbox** [comment]
Thank you, @funkpopo. I guess @karagi4 wants to create multiple nested sessions. If so, you only need to use the `a>b>c` format in `group` to create a large number of nested sessions. E.g: 

![image](https://user-images.githubusercontent.com/51009775/142823150-f0a0b196-8887-4710-9ab5-a71e25781be8.png)
lable: 1 group: a>b
lable: 2 group: a>b
label: 3 group: a>c
label: 4 group: a>d

then you will get: 
![image](https://user-images.githubusercontent.com/51009775/142824071-83a0b360-a964-4162-8f80-891e31b9beee.png)

**Comment by karagi4** [comment]
Yes, multiple nested sessions! It work, thx.

**Comment by funkpopo** [comment]
> Thank you, @funkpopo. I guess @karagi4 wants to create multiple nested sessions. If so, you only need to use the `a>b>c` format in `group` to create a large number of nested sessions. E.g:
> 
> ![image](https://user-images.githubusercontent.com/51009775/142823150-f0a0b196-8887-4710-9ab5-a71e25781be8.png) lable: 1 group: a>b lable: 2 group: a>b label: 3 group: a>c label: 4 group: a>d
> 
> then you will get: ![image](https://user-images.githubusercontent.com/51009775/142824071-83a0b360-a964-4162-8f80-891e31b9beee.png)

Oh, I'm sorry for that, got a little impatient for this question.
Just found out a solution for my lost sessions, thank you.

**Comment by kingToolbox** [comment]
@karagi4
Sorry, this is my fault, I didn't describe it clearly in the changelog. **At the beginning, `dot` was indeed used, but later considering that `IP` contains dots, in order to avoid conflicts, it was changed to `>`.** But I am glad that the problem has been solved. :smile:
