### ISSUE TITLE
Interface setup

### ISSUE THREAD

**Issue by Twink-Polar** [kingToolbox/WindTerm#31]
Loving the Linux beta release!

I've typically found myself removing the filer, session, transfer panes as they take up a lot of real estate on the screen. I personally like a clean interface, I'll keep the quick commands right at the bottom as they are really helpful. 

Would you consider an option of being able to put the panes like filer, session, transfer etc in a separate tab? Somewhere you can easily switch to all of those type options, use them and switch back.

**Comment by kingToolbox** [comment]
Thank you. A separate tab is a good idea, I will seriously consider this suggestion. For now, you can already rearrange the interface as you like. If you think these panes take up space, you can place multiple panes in the same dock through the configuration button above each pane. Just check the menu item to show or hide the corresponding pane in the current dock.

![image](https://user-images.githubusercontent.com/51009775/101597647-f8635500-3a31-11eb-90c9-86c58b02802c.png)

In addition, when you move the mouse to the vertical border of the dock, the cursor will change to a SplitHCursor. At this time, double-clicking the border line will automatically hide the current dock. Similarly, double-clicking the border again will show the dock.

The following shortcuts can also quickly display the pane:
| Pane | Shortcut |
| --- | --- |
| Filer | Alt+W, Alt+F |
| Outline | Alt+W, Alt+L |
| Sender | Alt+W, Alt+X |
| Session | Alt+W, Alt+S |
| Transfer | Alt+W, Alt+T |

**Comment by Twink-Polar** [comment]
Didn't realise you could double click on the border to make it go away (good to know). I tried double clicking on the border again but it didn't bring it back.

**Comment by kingToolbox** [comment]
After double-clicking to hide the pane, move the mouse to the left/right side, and when the cursor changes to a SplitHCursor, double-click again. Or you can press and drag it out when the cursor changes. you can try. 

This design is too concealed, not a good design, mainly because the planned control buttons has not yet been developed. I will make an gif to illustrate this and add control buttons in the status bar later to better show or hide the pane.

I have seriously considered the separate tab plan you suggested. I am afraid it might not work. The main reason is that the filer, transfer and sender pane is tightly bound to the currently active view, so placing it in a separate tab will break this connection. What do you think?

**Comment by Twink-Polar** [comment]
I think what you said is fair enough and understandable. 

Developing the hideaway/show option is maybe the course of action, which could be a quick win?

**Comment by kingToolbox** [comment]
Well, it would be better to switch the layout with one click, just like switching to the debugging layout when starting debugging in the IDE, and returning to the default layout after debugging. But I think the layout is usually fixed after adjusting the layout at the beginning of use.

In addition, I have been concerned about [Qt-Advanced-Docking-System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) for a long time, and I think it’s good. WindTerm 2.x series will switch to this docking system and redesign the interface. I hope you will like it then.

**Comment by Twink-Polar** [comment]
I'll close this one. V1.9.2 is great. Looking forward to what you do next.

**Comment by kingToolbox** [comment]
Thank you. Although this issue is closed, the redesign of the interface will still be developed in v2.x series. In addition, the proxycommand you mentioned in the discussion will be implemented too. There are still more than 600 new features in the future, such as auto-complete, search result lists, etc. It is expected that a NodeJS engine will be introduced in the second half of this year, and advanced features such as triggers and macros will also be implemented.

So let us work together to create a better future. I wish you a happy new year and best of everything.
