### ISSUE TITLE
SSH connection to MikroTik devices issue

### ISSUE THREAD

**Issue by 60jr31** [kingToolbox/WindTerm#32]
Hi! Whe i try to connect via SSH to different MikroTik devices whith different versions of RouterOS, after authorization, the WindTerm immediately closes. WindTerm version 1.9.

**Comment by kingToolbox** [comment]
Thank you. I analyzed the operations after authorizated and found no problems. From the phenomenon, it should be use a illegal pointer.

May I ask what operation system you are using? Linux or Windows?

**Comment by 60jr31** [comment]
I use Windows. In the Windows firewall, connections from WindTerm are allowed. This error occurs when connecting to a local MikroTik device as well as to a remote device. Thanx for the feedback.

**Comment by kingToolbox** [comment]
My pleasure. 

Would you please tell me the version of RouterOS and the version the opensshl in the RouterOs? I plan to install one for easy troubleshooting. This kind of problem is generally difficult to find if there is no environment to reproduce, and it may take a little long time, so please be patient.

In addition, Is WindTerm unable to connect to all versions of the RouteOs, and can other tools like putty connect normally?

**Comment by 60jr31** [comment]
Versions of routers on MikroTik devices, to which I tried to establish a ssh connection via WindTerm - 6.47.8, 6.45.7. Unfortunately, I don't know how to look at the version of the openssh of RouterOS. At the same time, putty connects via the ssh with all the versions of the RouterOS.

**Comment by 60jr31** [comment]
It looks like this.

https://user-images.githubusercontent.com/76503965/102996841-d50dcf00-4534-11eb-9bf3-d39b6579e823.mp4

**Comment by 60jr31** [comment]
Agent Authentication failed, please try another method.

For tests you can install Cloud Hosted Router version of RouterOS in Virtual Environment. I hope this helps, because your app is awesome and I want to switch to full use of it.
https://wiki.mikrotik.com/wiki/Manual:CHR
Thank you.

**Comment by kingToolbox** [comment]
Thank you for the video, which is very helpful for the initial determination of the problem. From the previous description, I thought it was an error in the login process. Only after seeing the video did I know that the login was successful.

The current progress is that with the help of the manual, I have successfully installed and run the RouterOS. And determined that the problem is as I speculated before, when negotiating the window size with the server, a null pointer appeared. In addition, I also found that user "amdin" and empty password cannot be used for automatic login.

I need some time to fix these two problems, it is expected to be less than a day, so please be patient, once the fix is completed, I will reply you here.

**Comment by kingToolbox** [comment]
The new version 1.9.2 has been released, please download and check, thank you.

In addition to fixing the crash, it also fixed the inability to log in automatically with user "admin", and I wrote a new RouterOS scheme so that highlighing, folding and outlining can be used.

In order to apply the new scheme to your RouteOS session, please set **"System"** to **"RouteOS"** in your RouteOS session's property dialog.

**Comment by 60jr31** [comment]
Perfectly. I checked that everything works. It is also authorized with the default account with the admin login without a password. Thank you very much. I wish you success in further development

**Comment by kingToolbox** [comment]
My pleasure. If you have any feature requests, please let me know. Hope WindTerm can make your work a little easier.
