### ISSUE TITLE
[3;J on clear command after scrolling up

### ISSUE THREAD

**Issue by lorenzo-patane** [kingToolbox/WindTerm#4]
Normally clear command works good, but if i scroll up and do clear command the terminal only print the terminal clear code ([3;J)
![Screenshot_1](https://user-images.githubusercontent.com/43727434/73610877-605c3a00-45dc-11ea-8f3d-b7de07eb1fda.png)

**Comment by lorenzo-patane** [comment]
Bug seems to be releated to this feature
![Screenshot_1](https://user-images.githubusercontent.com/43727434/73610989-8f26e000-45dd-11ea-9b00-bbd11c18d560.png)

**Comment by kingToolbox** [comment]
Thank you. I can not reproduce this bug and this is also very strange to me because control sequence of ED (Erase In Display) is 
```
CSI Ps J
Ps = 0, 1, 2, 3(xterm only)
```
I have never seen:
`CSI 3; J`

But it is easy to fix this temporarily. Please open **terminal\terms\xterm-256color.term** with editor and modify the line below:
`| (?<EraseScreen>                                 (?<type>                         \\d+)?                       J) # ED`
to
`| (?<EraseScreen>                                 (?<type>                         \\d+;?)?                    J) # ED`

If you use xterm.term, just do the same. 

In addition, Windterm only supports Ps equal to 0, 1, 2 now. 3 will be supported later.

**Comment by kingToolbox** [comment]
By the way, I think outline has nothing to do with this problem, because they are completely decoupled.

**Comment by lorenzo-patane** [comment]
Thank you for your reply, i will try

**Comment by kingToolbox** [comment]
This has been done in version 0.92.
