### ISSUE TITLE
mouse scroll alternate buffer bug

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#431]
With WindTerm 2.3.0 Prerelease x64 mouse don't scroll alternate buffer.

**Comment by kingToolbox** [comment]
Thank you. I have confirmed this issue and it will be fixed in the next prerelease version, I guess it is related to the `Qt 6.2.2` version.

If you do need this feature, you can temporarily use the [WindTerm_2.3.0_Prerelease_1_Windows_Portable_x86_32](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version, its function is normal.

**Comment by eugenov** [comment]
Suddenly I was not be able to reproduce with WindTerm_2.3.0_Prerelease_2_x64. Closing

**Comment by kingToolbox** [comment]
It's my fault, I fixed this in `WindTerm_2.3.0_Prerelease_2` but forgot to notify you. :smile:

**Comment by kingToolbox** [comment]
SORRY! `WindTerm_2.3.0_Prerelease_2` and `WindTerm_2.3.0_Prerelease_3` has a **serious SFTP bug** #487 and may cause file corruption after **uploaded**.

Please use the old versions or update to the [WindTerm_2.3.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version. Thank you.

**Comment by kingToolbox** [comment]
SORRY! `WindTerm_2.3.0_Prerelease_2` and `WindTerm_2.3.0_Prerelease_3` has a **serious SFTP bug** #487 and may cause file corruption after **uploaded**.

Please use the old versions or update to the [WindTerm_2.3.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version. Thank you.
