### ISSUE TITLE
Clicking session settings close Windterm

### ISSUE THREAD

**Issue by rpulikool** [kingToolbox/WindTerm#44]
When you click session settings it closes the windterm application all together

**Comment by kingToolbox** [comment]
Thank you. Does it mean clicking on **"Session Settings"** in the tab menu when the **Session Pane** is not visible? If yes, this bug has been fixed and will be released in the next version. Otherwise, please describe more trigger details.

The circumvention method now is to make sure the **Session Pane** is displayed at least once before clicking "Session Settings".

**Comment by rpulikool** [comment]
Yea that is correct. 

One more thing to add is can you please release a MAC version of WindTerm it will be very helpful

**Comment by kingToolbox** [comment]
The new version [2.0.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.0.0) has been released, please download and check, thank you.

The auto-login feature has been already implemented, you only need to check [Auto login next time](https://kingtoolbox.github.io/2020/01/23/auto-login/) when connecting to the server to save the login information.

In addition, please read the discussion [when will the macos release available](https://github.com/kingToolbox/WindTerm/discussions/46) to learn more about the MAC version.

**Comment by rpulikool** [comment]
Thank you i will check

**Comment by rpulikool** [comment]
The updates are really nice and works well.

Few feature request which will help to give option for look and feel for this product

* More Themes option
* Font Selection
* Option to enable/disable copy on select & mouse right click paste
Will there be a stable release soon?

**Comment by kingToolbox** [comment]
I am glad that the bug has been fixed and this issue can finally be closed, thank you very much.

The global setting interface will be provided in subsequent versions. At present, all the feature requests you mentioned can be set manually as follows:

- Option to specify the logs output directory
Please read [manual logging and automated logging](https://kingtoolbox.github.io/tags/logging/). In addition, in the `session property dialog - Shell/SSH/Telnet/Tcp/Serial - Terminal - Logging - Log file name`, you can click the browse button in the lineedit to set the log path you want to store.

- More Themes option
I am not sure what the options you are referring to. But if you know Qss(Qt style sheet), then you can completely customize every detail of the interface. You can imitate the existing themes, such as `\WindTerm_2.0.0\global\themes\dige-black\gui.theme` and so on.

- Font Selection
All fonts and colors are also customizable. You can modify the font to any font you want. Just open `\WindTerm_2.0.0\global\themes\dige-black\scheme.theme` then search and modify **"text.default"**, **"terminal.text"**.

- Option to enable/disable copy on select & mouse right click paste
`select-to-copy` and `middle-click-to-paste` is disabled by default on Windows. Set **"text.autoCopySelection"** in "\WindTerm_2.0.0\global\wind.config" to **true** to enable it and **false** to disable it. You can read #19 for more detailed information.

There are still many important functions that need to be completed and merged. I expect to release v2.0.0 in late January. In addition, although v2.0.0_Prerelease_1 is a prerelease version, it is also very stable.

**Comment by rpulikool** [comment]
Thank you for all the updates. I will check if i can edit to create the themes or do you know a source from where i can copy paste the qss files

**Comment by kingToolbox** [comment]
You can use the default themes of WindTerm as a template. For example, goto `WindTerm-Install-Path/global/themes`, there are three themes: dige-black, dige-black-and-white, dige-white. Copy any of these folders as a new one and rename the copied folder as "rpulikool", you will get a new theme "rpulikool" and can switch to it through menu item `View - Color Themes - rpulikool`. After that, you can modify the theme as you like.

**gui.theme**: Control the interface appearance, Qt [style sheets](https://doc.qt.io/qt-5/stylesheet-reference.html) and [examples](https://doc.qt.io/qt-5/stylesheet-examples.html);
**icon.theme**: Control the icons appearance and color, If you do not need to modify the icon, you can usually ignore it.
**scheme.theme**: Control the content of view, like text, margin, highlight and so on. You can refer to [vscode semantic-themeing](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#semantic-theming).

**Note**:
After the modification is completed, you need to restart or switch to another theme through the menu and then switch back to see the modification result.

**Comment by rpulikool** [comment]
One more feedback that will help for the product

* Remove the numbers on the menu bar
* Make the tabs when they are connected like ssh little bigger and maybe colour it differently so we know which session is active.

**Comment by kingToolbox** [comment]
Sorry for the late reply. I have been busy preparing for [v2.0.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.0.0) during this period. The stable version may be delayed for a while, and I expect it to be released in mid-February now.

- Remove the numbers on the menu bar
Due to the particularity of the terminal many shortcut keys are occupied by the server, especially the **ctrl** series, so the **alt** series is used in WindTerm, such as `alt+f` instead of `ctrl+f`. And usually the **alt** series will be used for the shortcut keys of the menubar. So in order to solve this problem, the digital series was used instead.
The shortcut keys of the menubar is very important for using the full keyboard to operate WindTerm. I think I will keep this design until there is a better solution. 
If you want to remove it yourself, you can open `WindTerm-Install-Path/terminal/configs/menu.config` and delete the number, such as ` (&1)`. 
``` json
	"Kit" : [
		{ "Menu" : "Session (&1)" },
		{ "Menu" : "Edit (&2)" },
                ...
         ]
```
- Make the tabs when they are connected like ssh little bigger and maybe colour it differently so we know which session is active
The top of the activity tab is already marked by a thick blue horizontal line. 
![image](https://user-images.githubusercontent.com/51009775/106850393-6739f300-66ef-11eb-968a-5a449cc535ff.png)

Thank you very much for your suggestions. The Mac version will be released after April, please keep attation.

**Comment by rpulikool** [comment]
Thanks for the update, I wish and certainly sure this product is going to improve 10 times

**Comment by kingToolbox** [comment]
It looks like all the problems in this post have been solved. This issue will be closed and welcome to continue submitting new issues and feature requests. Thank you! :smiley:

**Comment by kingToolbox** [comment]
@rpulikool I am happy to inform you that the MacOS version of WindTerm has been released. Please download and use [WindTerm_2.1.0_Prerelease_6_MacOS_Portable](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease). Feedback is welcome if you have any questions. In this version, `right-click-to-paste` is also supported. Set **"terminal.rightClickAction"** in `WindTerm_install_path/profiles/default.v10/user.config` or `WindTerm_install_path/global/wind.config` to **"PasteText"** to enable it. Thank you.
