### ISSUE TITLE
When using 1.9.2 linux to exit with more, the interface is all garbled

### ISSUE THREAD

**Issue by EverythingGoesWithTheFlow** [kingToolbox/WindTerm#50]
When using 1.9.2 linux to exit with more, the interface is all garbled

**Comment by kingToolbox** [comment]
Thank you.

I tried to use `more` to view a long file under Linux, but whenever I use `q or Q or ctrl+c` to exit, everything is ok. Please correct me if I understand it wrongly. Can you describe in detail your system version and the detailed steps to reproduce this problem?

**Comment by EverythingGoesWithTheFlow** [comment]
I don't know if I did it by mistake
![{014B328A-F17C-4385-98A7-66CB576A981E} png](https://user-images.githubusercontent.com/54532769/105388369-877aa400-5c51-11eb-9447-4891db8c12f8.jpg)

**Comment by EverythingGoesWithTheFlow** [comment]
♦ID_♦ ┴▒⎼␌␤▒⎼(64) COLLATE ┤├°8_␉␋┼ NOT NULL,
  ♦PROC_DEF_ID_♦ ┴▒⎼␌␤▒⎼(64) COLLATE ┤├°8_␉␋┼ NOT NULL,
  ♦PROC_INST_ID_♦ ┴▒⎼␌␤▒⎼(64) COLLATE ┤├°8_␉␋┼ NOT NULL,
  ♦EXECUTION_ID_♦ ┴▒⎼␌␤▒⎼(64) COLLATE ┤├°8_␉␋┼ NOT NULL,
  ♦ACT_ID_♦ ┴▒⎼␌␤▒⎼(255) COLLATE ┤├°8_␉␋┼ NOT NULL,
  ♦TASK_ID_♦ ┴▒⎼␌␤▒⎼(64) COLLATE ┤├°8_␉␋┼ DEFAULT NULL,
  ♦CALL_PROC_INST_ID_♦ ┴▒⎼␌␤▒⎼(64) COLLATE ┤├°8_␉␋┼ DEFAULT NULL,
  ♦ACT_NAME_♦ ┴▒⎼␌␤▒⎼(255) COLLATE ┤├°8_␉␋┼ DEFAULT NULL,
  ♦ACT_TYPE_♦ ┴▒⎼␌␤▒⎼(255) COLLATE ┤├°8_␉␋┼ NOT NULL,
  ♦ASSIGNEE_♦ ┴▒⎼␌␤▒⎼(255) COLLATE ┤├°8_␉␋┼ DEFAULT NULL,
  ♦START_TIME_♦ ␍▒├␊├␋└␊ NOT NULL,
  ♦END_TIME_♦ ␍▒├␊├␋└␊ DEFAULT NULL,
  ♦DURATION_♦ ␉␋±␋┼├(20) DEFAULT NULL,
  ♦TENANT_ID_♦ ┴▒⎼␌␤▒⎼(255) COLLATE ┤├°8_␉␋┼ DEFAULT '',
[⎼⎺⎺├@␋≥␉⎻1␊4┤├␋⎻59┴␉␋␌┤┤8┤␍≥ ·]# ┌⎽
␌┤⎼┌.⎻┌  ␍⎽.⎽─┌  ├_␊└␊⎼±␊┼␌≤_D┤├≤_⎺°°␋␌␊⎼.⎽─┌  ├␊⎽├
[⎼⎺⎺├@␋≥␉⎻1␊4┤├␋⎻59┴␉␋␌┤┤8┤␍≥ ·]# ┌⎽
␌┤⎼┌.⎻┌  ␍⎽.⎽─┌  ├_␊└␊⎼±␊┼␌≤_D┤├≤_⎺°°␋␌␊⎼.⎽─┌  ├␊⎽├
[⎼⎺⎺├@␋≥␉⎻1␊4┤├␋⎻59┴␉␋␌┤┤8┤␍≥ ·]# ┌⎽
␌┤⎼┌.⎻┌  ␍⎽.⎽─┌  ├_␊└␊⎼±␊┼␌≤_D┤├≤_⎺°°␋␌␊⎼.⎽─┌  ├␊⎽├
[⎼⎺⎺├@␋≥␉⎻1␊4┤├␋⎻59┴␉␋␌┤┤8┤␍≥ ·]# 

I don't know if I did it by mistake

**Comment by kingToolbox** [comment]
I guess you used `more or cat` to view the binary file?

When using `more or cat` the binary file, a large number of binary codes will be mistakenly treated as TERM control sequences, especially when the binary code triggers the change of the terminal's character sets, like `SI SO SS2 and so on`. This will occasionally cause the text displayed in `DEC Special Character and Line Drawing Set` to look like garbled characters.

You can enter **`echo -e "\033o"`** to simulate this. And enter **`echo -e "\017"`** to return to the normal display state.

Other terminals also have this problem, but their state machine is handwritten, so they are more strict. However, WindTerm uses a general regular expression engine to provide better versatility, so that all TERM control sequences can be configured by external files `windterm_install_path/terminal/terms`. So although it is possible for WindTerm, it is not strictly limited.

There is currently no good way to solve this problem. You must **reconnect** or manually enter **`echo -e "\017"`** to restore the default character set. But I will provide a tool button or menu item in the future to help restore the correct display state.

**Comment by EverythingGoesWithTheFlow** [comment]
Good thank you

**Comment by kingToolbox** [comment]
Anytime, and any issues are welcome.
