### ISSUE TITLE
How to save Username only

### ISSUE THREAD

**Issue by AntoninHL** [kingToolbox/WindTerm#501]
Hello,

first of all, many thanks for the impressive work you made on this tool. Really cool!

I have a question related to the creds storage.
Is it possible to only store username in SSH session?

Thanks

A./

**Comment by kingToolbox** [comment]
Sorry for the late reply. Because I've been sick recently.

If you don't want to use automatic login, you can set `Host` to `user@hostname` when you create a new session to save only the username. For example `root@192.0.1.1`, you can give it a try.

If you still have questions, please feel free to ask. Thank you.
