### ISSUE TITLE
WindTerm  crash

### ISSUE THREAD

**Issue by lcmgithub** [kingToolbox/WindTerm#516]
Win10 21H1 system WindTerm  accident crash
[dmp.zip](https://github.com/kingToolbox/WindTerm/files/8066068/dmp.zip)

**Comment by kingToolbox** [comment]
Thank you very much for the detailed crash reports. I have tried to analyzed the minidump files, but unfortunately the minidump files could not be loaded correctly.

But I noticed some details, that there are two crash reports reported crashing app named `WindTerm_Win10_Conpty.exe`, which is the name used before the `WindTerm_2.3.0` version. So I guess it is possible that you have mixed the new version with the old version, because the new version cannot use the dynamic link libraries of the old version, and caused a crash.

So please download the [WindTerm_2.3.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) version again. If you need the old data, please copy the folder `profiles` from the old version to the new version.

Please let me know if there are still crashes. Thank you.

BTW:
For `Win 10 21H1`, Please use the `WindTerm_2.3.0_x86_64` version instead of the `WindTerm_2.3.0_x86_32` version if you can.

**Comment by lcmgithub** [comment]
I deleted the old version and re-downloaded the 2.3.0 version, after using it for a while, the crash problem still exists.
[5b1e7028-141f-4337-b9dc-00653c1a36fe.zip](https://github.com/kingToolbox/WindTerm/files/8085871/5b1e7028-141f-4337-b9dc-00653c1a36fe.zip)

**Comment by kingToolbox** [comment]
Thank you very much. I have analyzed the new minidump file and found that the reason **may be** that your`CPU` does not support the `_mm_max_epu16` instruction of `SSE 4.1`. May I know what type of CPU do you have?

**Comment by lcmgithub** [comment]
My CPU Info:
Intel(R) Core(TM)2 Duo CPU E6550 @ 2.33GHz 2.33 GHz

**Comment by kingToolbox** [comment]
According to the `intel`'s documentation, your `CPU` does not support the `SSE 4.1` instructions, that's the reason for the crash.

I will try to rewrite this part of the code to be compatible with older CPUs. If all goes well, I will release `WindTerm_2.4.0_Prerelease_1` this week or next week. Please stay tuned, thank you.
