### ISSUE TITLE
Installation fail on macOS (11.6.2)

### ISSUE THREAD

**Issue by gonzalez-ben** [kingToolbox/WindTerm#518]
Hi,

I would try this app but installation on macOS fails instantly. I'm using a macbook pro 2020 with Big Sur (11.6.2)
![Capture d’écran 2022-02-15 à 09 47 07](https://user-images.githubusercontent.com/61469106/154026529-3d545df5-092b-4ecd-95c2-9983bc77592e.png)

Someone could help me please ?

Best regards,
Ben

**Comment by kingToolbox** [comment]
This is only because `WindTerm` is a free software and has not yet applied for the Apple's developer certificate. If you trust `WindTerm`, you can read [3 façons de corriger «macOS ne peut pas vérifier que cette application est exempte de logiciels malveillants»](https://www.neuf.tv/3-facons-de-corriger-macos-ne-peut-pas-verifier-que-cette-application-est-exempte-de-logiciels-malveillants-gadgets-a-utiliser), the article explains how to install software without a certificate.

If you still have questions, please let me know. Thank you.

**Comment by gonzalez-ben** [comment]
Thank you for this tips, I didn't know this. It's working fine and it's clearly not an issue.
