### ISSUE TITLE
[Feature Request]Use ctrl-d to close the tab

### ISSUE THREAD

**Issue by KagurazakaNyaa** [kingToolbox/WindTerm#526]
In most ssh sessions, pressing ctrl-d [EOF] means logout, so many people will use this shortcut to exit the session.
The current behavior of WindTerm is that after using ctrl-d to log out of the ssh session, pressing it again will result in a warning "Remote channel is closed".
The behavior of xshell for this operation is that pressing ctrl-d again after the session is disconnected will close the session. And Microsoft Terminal's behavior is to directly close the session after the session is disconnected.
Is it possible to achieve xshell-like behavior where pressing ctrl-d again in a disconnected session means closing this session?

**Comment by kingToolbox** [comment]
I see. Pressing the `Ctrl+D` key twice to close a tab is acceptable to me, as it is the user's own action and intent, rather than **automatically** closing the tab once `logging out` is detected.

I will provide this feature in `WindTerm_2.4.0_Prerelease_1` this week or next, please stay tuned, thank you.

BTW:
`Ctrl+Shift+W` closes tabs and `Ctrl+Shift+Q` closes windows, which is an imitation of `Cmd+W` and `Cmd+Q` of `macOS` system. It is really difficult to find a suitable shortcut key for `WindTerm`, most of the suitable keys are occupied by the remote end, such as `Ctrl+C`.

**Comment by kingToolbox** [comment]
Sorry for the late reply, because I have some personal matters to attend to recently, the progress of development has been delayed.

Now the new [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) supports pressing the shortcut key `Ctrl+D` to close any disconnected session tab, which also means that you can double-click the shortcut `Ctrl+D` to close an already connected session. Please download and use it, thank you.
