### ISSUE TITLE
Would you consider adding more feature to WindEdit?

### ISSUE THREAD

**Issue by bpan2020** [kingToolbox/WindTerm#54]
Would you consider adding more feature to WindEdit? 

1. Jump to definition, just like vscode.
2. Display 'search all' output to output window, and support multiple output window for different search result.

**Comment by kingToolbox** [comment]
Yes for sure. WindEdit has excellent features such as viewing and editing large text and long lines. It can use only 10mb memory to open a 7gb file containing 2.5 billion lines or a 7gb file containing one line or 700gb file now. I have never seen this ability in other text editors. I think it is useful for many developers. In fact, since the last v0.9 was released one year ago, WindEdit has never stopped adding new features and fixing bugs. After the new WindTerm v2.0.0 is released, the new WindEdit v1.0.0 will also be released soon. The good news is that the new features include the second feature you need.

In a sense, WindTerm and WindEdit are actually the same tool. The only difference is that WindTerm reads text from the network and processes, and WindEdit reads text from the files. WindTerm and WindEdit share the same source code and features and bug fixes during development, and only compile different components for release.

As I said, the second "search all" feature is under development. But the first feature is a little more difficult. If you need to jump to definition accurately, WindEdit must build AST(Abstract syntax tree) for the source code first. Before the advent of 
 [LSP(Language Server Protocol)](https://microsoft.github.io/language-server-protocol/), I thought of using Flex and Bison or ANTLR to achieve this. But now WindEdit
 only need to support LSP. This work is expected to be in the third quarter after the script engine and plug-ins system are implemented, so please be patient.

Features of the WindEdit v1.0.0 include better performance, black theme, search results pane, and more language support, such as Java, Javascript, Typescript, PHP, SQL, Bash script, Go, Ruby, Swift, MATLAB and so on. Of course, there is also Linux version. The prerelease v1.0.0 is expected to be released in early March, and the stable v1.0.0 will be released in early April. Welcome to download and use.

BTW, you can submit new feature requests directly in [WindEdit issues](https://github.com/kingToolbox/DIGEdit/issues), and I will deal with them as soon as possible too. Thank you.

**Comment by bpan2020** [comment]
Great, really appreciate your effort.

**Comment by hongnod** [comment]
Would you consider add ssh to WindEdit like vscode's Remote SSH plugin  and outline?
if yes,that would be very very nice.

**Comment by kingToolbox** [comment]
No, I do not intend to do this. VSCode remote needs install remoteAgent in the server.

![image](https://user-images.githubusercontent.com/51009775/110863251-618d8980-82fb-11eb-8a49-153a5d8a8705.png)

I have always believed that a client should be completely independent of the server and should not intrude into the server. After all, if a feature depends on remote agents or scripts, then its use is restricted. In many cases, the server does not provide permissions, or the server has a higher importance and should not do this. So I don't quite agree with this kind of design, like VSCode remote and iterm2 shell integration and so on. I hope everything is done just in WindTerm itself, even if some features cannot be implemented.

I said WindTerm and WindEdit are actually one tool. All functions are integrated from the beginning of the design and implementation.  So WindTerm and WindEdit will go further in some features like editing and managing remote files, but not in other features like remote debug.

In addition, after the plug-in system is completed, similar to VSCode remote can be completed by a third-party plug-in.

**Comment by hongnod** [comment]
It looks like not a same thing,what I mean is as following:
![ksnip_20210312-075519](https://user-images.githubusercontent.com/6680267/110871131-c1d6f800-8308-11eb-9c58-e1fd8d73fab6.png)

**Comment by hongnod** [comment]
I see,it's same. I recall this feature request

**Comment by kingToolbox** [comment]
According to my plan, WindTerm and WindEdit will eventually become a unified tool. Not limited to this, there will be local filer (like everything.exe and explorer.exe), remoter filer (like FTP/FTPS/SFTP client) and browser and other modules added.

**Comment by hongnod** [comment]
nice.

**Comment by bpan2020** [comment]
Can WindEdit open local txt files and how?


Thanks,
Berg Pan (panqihe)

发件人: kingToolbox ***@***.***>
发送时间: 2021年2月25日 0:56
收件人: kingToolbox/WindTerm ***@***.***>
抄送: Berg Pan ***@***.***>; Author ***@***.***>
主题: Re: [kingToolbox/WindTerm] Would you consider adding more feature to WindEdit? (#54)


Yes for sure. WindEdit has excellent features such as viewing and editing large text and long lines. It can use only 10mb memory to open a 7gb file containing 2.5 billion lines or a 7gb file containing one line or 700gb file now. I have never seen this ability in other text editors. I think it is useful for many developers. In fact, since the last v0.9 was released one year ago, WindEdit has never stopped adding new features and fixing bugs. After the new WindTerm v2.0.0 is released, the new WindEdit v1.0.0 will also be released soon. The good news is that the new features include the second feature you need.

In a sense, WindTerm and WindEdit are actually the same tool. The only difference is that WindTerm reads text from the network and processes, and WindEdit reads text from the files. WindTerm and WindEdit share the same source code and features and bug fixes during development, and only compile different components for release.

As I said, the second "search all" feature is under development. But the first feature is a little more difficult. If you need to jump to definition accurately, WindEdit must build AST(Abstract syntax tree) for the source code first. Before the advent of
LSP(Language Server Protocol)<https://microsoft.github.io/language-server-protocol/>, I thought of using Flex and Bison or ANTLR to achieve this. But now WindEdit
only need to support LSP. This work is expected to be in the third quarter after the script engine and plug-ins system are implemented, so please be patient.

Features of the WindEdit v1.0.0 include better performance, black theme, search results pane, and more language support, such as Java, Javascript, Typescript, PHP, SQL, Bash script, Go, Ruby, Swift, MATLAB and so on. Of course, there is also Linux version. The prerelease v1.0.0 is expected to be released in early March, and the stable v1.0.0 will be released in early April. Welcome to download and use.

BTW, you can submit new feature requests directly in WindEdit issues<https://github.com/kingToolbox/DIGEdit/issues>, and I will deal with them as soon as possible too. Thank you.

**Comment by kingToolbox** [comment]
WindEdit is a normal text editor, and there is no difference between VsCode and GVim, you can use the open dialog to open the file (`Menubar - File - Open File...` `ctrl+O`), or drag and drop the file to WindEdit to open it.

**Comment by bpan2020** [comment]
When will the new feature in WindTerm be available in WindEdit. You said in previous emails that the new feature in WindTerm will be added to WindEdit.

Thanks,
Berg Pan (panqihe)

发件人: kingToolbox ***@***.***>
发送时间: 2021年5月24日 19:28
收件人: kingToolbox/WindTerm ***@***.***>
抄送: Berg Pan ***@***.***>; Author ***@***.***>
主题: Re: [kingToolbox/WindTerm] Would you consider adding more feature to WindEdit? (#54)


WindEdit is a normal text editor, and there is no difference between VsCode and GVim, you can use the open dialog to open the file (Menubar - File - Open File... ctrl+O), or drag and drop the file to WindEdit to open it.

**Comment by kingToolbox** [comment]
Yes, every suitable new feature will be added to WindEdit. I just released a new prerelease version of WindTerm 2.1.0, I think I will refocus on developing WindEdit after WindTerm v2.2.0. The time should be in July and August. But my recent development progress is unstable, Just like `X/Y/Z Modem`, this feature took an extra month to complete. so I cannot guarantee too much.

**Comment by bpan2020** [comment]
Sounds great! I can’t wait to have a try. Really appreciate your effort!

Thanks,
Berg Pan (panqihe)

发件人: kingToolbox ***@***.***>
发送时间: 2021年5月28日 6:12
收件人: kingToolbox/WindTerm ***@***.***>
抄送: Berg Pan ***@***.***>; Author ***@***.***>
主题: Re: [kingToolbox/WindTerm] Would you consider adding more feature to WindEdit? (#54)


Yes, every suitable new feature will be added to WindEdit. I just released a new prerelease version of WindTerm 2.1.0, I think I will refocus on developing WindEdit after WindTerm v2.2.0. The time should be in July and August. But my recent development progress is unstable, Just like X/Y/Z Modem, this feature took an extra month to complete. so I cannot guarantee too much.

**Comment by kingToolbox** [comment]
Hello, as I said, I will refocus on developing WindEdit after WindTerm 2.1.0 or 2.2.0. Today I just released [WindEdit_1.0.0_Prerelease_1](https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelase), which is **a brand new WindEdit that combines the old WindEdit and WindTerm.** Every new feature of WindTerm developed in the past year and a half has been added to the new WindEdit. And also provides a MacOS version. 

In fact, from the beginning, WindEdit and WindTerm are such a unity. It's just been released separately. 

This will be a good start. In the next time, I will add a lot of various language configurations first, such as Go, Swift, Java, JavaScript, Html, XML and so on, so that each language can support coloring, folding, outlining and auto-completion. Then I will finish rewriting the search module and output window, as @bpan2020 suggested. There are other features that will be added to WindEdit_1.0.0. I believe that WindEdit will become a good text editor that can be used daily.

**Comment by kingToolbox** [comment]
The newly released [WindEdit_1.0.0_Prerelease_1](https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelase) already contains all the new features. I will continue to develop new features for WindEdit in the future. If you have any needs, welcome to continue submitting new issues and feature requests in the [WindEdit issues](https://github.com/kingToolbox/WindEdit/issues), thank you.

**Comment by bpan2020** [comment]
Really appreciate your effort!

Thanks,
Berg Pan (panqihe)

发件人: kingToolbox ***@***.***>
发送时间: 2021年7月18日 9:29
收件人: kingToolbox/WindTerm ***@***.***>
抄送: Berg Pan ***@***.***>; Mention ***@***.***>
主题: Re: [kingToolbox/WindTerm] Would you consider adding more feature to WindEdit? (#54)


Hello, as I said, I will refocus on developing WindEdit after WindTerm 2.1.0 or 2.2.0. Today I just released WindEdit_1.0.0_Prerelease_1<https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelase>, which is a brand new WindEdit that combines the old WindEdit and WindTerm. Every new feature of WindTerm developed in the past year and a half has been added to the new WindEdit. And also provides a MacOS version.

In fact, from the beginning, WindEdit and WindTerm are such a unity. It's just been released separately.

This will be a good start. In the next time, I will add a lot of various language configurations first, such as Go, Swift, Java, JavaScript, Html, XML and so on, so that each language can support coloring, folding, outlining and auto-completion. Then I will finish rewriting the search module and output window, as @bpan2020<https://github.com/bpan2020> suggested. There are other features that will be added to WindEdit_1.0.0. I believe that WindEdit will become a good text editor that can be used daily.

**Comment by bpan2020** [comment]
I tried the editor. It's great. Would you consider adding more features to WindEdit? Such as,
1, List all the files in the directory of the active editing file, just like  the list of open files on the explore window.
2, List all the lines with the search word into a output window, and can open more windows for other searching results.

Thanks,
Berg Pan (panqihe)

发件人: kingToolbox ***@***.***>
发送时间: 2021年7月21日 0:51
收件人: kingToolbox/WindTerm ***@***.***>
抄送: Berg Pan ***@***.***>; Mention ***@***.***>
主题: Re: [kingToolbox/WindTerm] Would you consider adding more feature to WindEdit? (#54)


The newly released WindEdit_1.0.0_Prerelease_1<https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelase> already contains all the new features. I will continue to develop new features for WindEdit in the future. If you have any needs, welcome to continue submitting new issues and feature requests in the WindEdit issues<https://github.com/kingToolbox/WindEdit/issues>, thank you.

**Comment by bpan2020** [comment]
I tried the editor. It's great. Would you consider adding more features to it?
1, List all the files in the directory of the active editing file, just like  the list of open files on the explore window.
2, List all the lines with the search word into a output window, and can open more output windows for other searching results of search in file.

Thanks,
Berg Pan (panqihe)

发件人: kingToolbox ***@***.***>
发送时间: 2021年7月21日 0:51
收件人: kingToolbox/WindTerm ***@***.***>
抄送: Berg Pan ***@***.***>; Mention ***@***.***>
主题: Re: [kingToolbox/WindTerm] Would you consider adding more feature to WindEdit? (#54)


The newly released WindEdit_1.0.0_Prerelease_1<https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelase> already contains all the new features. I will continue to develop new features for WindEdit in the future. If you have any needs, welcome to continue submitting new issues and feature requests in the WindEdit issues<https://github.com/kingToolbox/WindEdit/issues>, thank you.
