### ISSUE TITLE
Support outline and folding on different shells and custom prompts

### ISSUE THREAD

**Issue by 0ffz** [kingToolbox/WindTerm#57]
It seems the outline and folding features don't work with different shells like fish and zsh, as well as customized prompts such as https://starship.rs/.

I assume there's something manually parsing the text to achieve this. I wonder if perhaps there's a way to generalize it more, though I don't know the inner workings and understand if it's hard to do!

**Comment by 0ffz** [comment]
Ooh, I've just noticed this seems to be configurable in schemes (haha that was fast). Feel free to close this issue!

**Comment by 0ffz** [comment]
Since I'm already here, perhaps it would be worth renaming the `linux` syntax scheme to `bash`? I feel that's a bit more descriptive.

**Comment by kingToolbox** [comment]
Yes, schemes are highly configuarable. In fact almost everything in WindTerm can be customized, only need to know a little regular expression and javascript. If you need customization, here is a brief guide:

| File  | Function |
| ------------- | ------------- |
| global/themes/*/gui.theme  | Define GUI, like menus, buttons, panes and so on |
| global/themes/*/icon.theme  | Define icons of panes, outline tree and so on |
| global/themes/*/scheme.theme  | Define text appearance, like default font, line numbers, fold and so on |
| global/wind.actions  | Define every action in WindTerm, like Terminal.ReconnectSession and so on |
| global/wind.keymaps | Define every shortcut key in WindTerm |
| terminal/configs/*.config | Define menu, toolbar and statusbar |
| terminal/protocol/*.protocol | Define protocols, like how to parse Telnet protocol |
| terminal/scheme/*/\*.fold | Define fold of scheme  |
| terminal/scheme/*/\*.lexer | Define styling of scheme |
| terminal/scheme/*/\*.outline | Define outline of scheme |
| terminal/scheme/*/\*.pairs | Define pairs of scheme, like brackets and so on |
| terminal/terms/*.term | Define terms, like vt100, vt220, xterm and so on |

WindTerm should be the only client that supports external protocols and terms customization. This means that you can extend  private protocol and terms yourself. WindTerm also has the most powerful shortcut key customization as I explained it before in issue #13. More detailed documents will be prepared in the future. 

The name "linux" is used because I want to use this as a base scheme to write schemes for every distribution of Linux/Unix/BSD, like "Ubuntu 18.04", "CentOS 7" and etc., and even defines how to parse and styling the output of each command, like cat, ping, etc.. When you connect to different distribution in the future, you only need to select the corresponding scheme. Then you can have different but most accurate folds, colorings, etc., especially automatic completion of commands. Of course this will be a big project, and I hope that the community can complete it with me.

We have always said **dumb** terminals. But I think WindTerm can also be very **smart**. One day WindTerm can know how to color the current output, know which text are URLs, IPs, files, folders and support to take action on it, like ping ip, rm files and etc., know how to automatically complete the current input commands, know how to quickly jump to other directories, even know how to find errors in the output and email you, etc. I know that some work can now be achieved through zsh, fish or scripts, but when managing a large number of servers, it is much more convenient for these tasks to be done by WindTerm instead of installing external shells or distributing scripts to each server. 

Let WindTerm be the smartest rather than dumb terminal is my ultimate goal of developing WindTerm.

**Comment by kingToolbox** [comment]
The stable version [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0) has been finally released, and more setting UI and detailed documents of customization will be prepared in the future. Thank you!

**Comment by satanaileo** [comment]
> Since I'm already here, perhaps it would be worth renaming the `linux` syntax scheme to `bash`? I feel that's a bit more descriptive.

Hello, I am not familiar with regular expressions. Can you explain how to configure the fold function of zsh and how to make it work? I tried a lot and didn't make any sence.
