### ISSUE TITLE
WSL2 Ubuntu `jupyter-lab` doesn't display properly

### ISSUE THREAD

**Issue by LavendaRaphael** [kingToolbox/WindTerm#596]
In WSL2 Ubuntu, when start `jupyter-lab`, the output log message will disappeared like this
![2022-03-14_222020](https://user-images.githubusercontent.com/44314340/158191646-2804517c-99ff-4ce6-ad6c-9b795ef124e7.png)
![2022-03-14_222040](https://user-images.githubusercontent.com/44314340/158191660-5e2758a9-fa6b-43c6-8bb3-0ea4186d8201.png)

**Comment by Rubp-007** [comment]
Hi @LavendaRaphael, I had a similar problem. When I launch Jupyter Lab/Notebook from WSL, there were some errors printed on the terminal, but they flashed away quickly, resulting in a blank screen like yours.

It turns out to be a [known issue for Jupyter on WSL](https://github.com/jupyterlab/jupyterlab/issues/10413). The qucik fix is to add the `--no-browser` option as suggested [here](https://stackoverflow.com/questions/50882266/using-jupyter-with-windows-subsystem-for-linux):  `jupyter notebook --no-browser`

**Comment by LavendaRaphael** [comment]
> Hi @LavendaRaphael, I had a similar problem. When I launch Jupyter Lab/Notebook from WSL, there were some errors printed on the terminal, but they flashed away quickly, resulting in a blank screen like yours.
> 
> It turns out to be a [known issue for Jupyter on WSL](https://github.com/jupyterlab/jupyterlab/issues/10413). The qucik fix is to add the `--no-browser` option as suggested [here](https://stackoverflow.com/questions/50882266/using-jupyter-with-windows-subsystem-for-linux): `jupyter notebook --no-browser`

Thank you, it works!
