### ISSUE TITLE
Whether ZModem can be supported

### ISSUE THREAD

**Issue by bilinxing** [kingToolbox/WindTerm#60]
I prefer lrzsz to sftp, which allows me to upload or download files from the current directory at any time。ZModem is a really good feature, I hope to support！

**Comment by kingToolbox** [comment]
Duplicate of #27.

ZModem happens to be in the [roadmap](https://github.com/kingToolbox/WindTerm#roadmap) of the next version 2.1.0. So this feature will definitely be supported. The development will be divided into two parts, first will support ASCII/XModem/YModem, these protocols are also supported by lrzsz, then support ZModem. Because there is no suitable library that can be used directly, it must be completely developed in accordance with the X/Y/ZModem protocol. So it will take a long time, and it is expected to be released in early April. Please keep follow and thank you.

**Comment by bilinxing** [comment]
Great! Looking forward to it! Thank you so much!

**Comment by kingToolbox** [comment]
The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and supports ZModem well. You can download and check, thank you!

**Comment by bilinxing** [comment]
Great, I'll try it, thanks a lot!

**Comment by kingToolbox** [comment]
If you think ZModem still needs new functions or encounter problems, please let me know. I will implement it as soon as possible. In addition, XModem and YModem are under development and should be completed soon. And will be published in version 2.1.0_Prerelease_3.

**Comment by bilinxing** [comment]
I have been using it for a week, it works very well, no problems for now, if I encounter any problems I will give feedback, thank you very much!

**Comment by kingToolbox** [comment]
Thank you for bringing me such a good news. The bug of garbled characters in the transmission of non-ASCII file names is being resolved. I hope that a more complete rz/sz feature will be available soon. :smile:
