### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by rpulikool** [kingToolbox/WindTerm#61]
I found a strange issue working with 2..0.0 release. Using the clear command to clear the screen it comes to the same prompt while i see its working on other ssh utilities

[test1@test1 ~]$ clear
[test1@test1 ~]$ 
[test1@test1 ~]$ which clear
/usr/bin/clear

**Comment by kingToolbox** [comment]
Would you like to describe the difference with other ssh utilities in more detail? I compared PuTTY and did not observe any difference. Thank you.

**Comment by rpulikool** [comment]
I have used putty and Terminus both it seems to work...meaning it clear the screen..however windterm put me to the next prompt

**Comment by kingToolbox** [comment]
After you enter the `clear` command, terminals will do the following three steps:

- Clear the scrollback
- Put the current screen to the scrollback
- Make the last prompt line on the top of the screen

So you can try to type `clear` several times to see if there is only one line contains `clear` and one line of command prompt left in the view.

Another test is to enter `seq 1 100` first, then enter `clear` to see what is left on the current screen?

**Comment by rpulikool** [comment]
93
94
95
96
97
98
99
100
[test1@test1~]$ clear
[test1@test1~]$ 
[test1@test1~]$ 
[test1@test1~]$ 

Nope its not working maybe some settings let me download again and try

**Comment by kingToolbox** [comment]
Have you tried Ctrl+L? Can the screen be cleared correctly? If this doesn't work either, please do the following:

- Open the ssh session property dialog.
- In Terminal / Logging, check the "Log all session output".
- Connect to the host and execute "seq 1 100" and "clear" serveral times.
- Close the tab or app.
- Open the folder WindTerm-Install-Path/profiles/default.v10/terminal/logs/Session-Name
- Confirm that the latest log file exists and contains content such as "erasescreen".
- Upload your log file in your comment here. You can zip it before upload.

In addition, please don't worry, the log will not record any private information such as usernames and password, and you can check this before uploading the log file. If you are worried about PS1, you can replace all `[user@host ~]` with `[xxxx@xxxx ~]` before upload. You can also do the same for the others sensitive information. Thank you very much.

**Comment by rpulikool** [comment]
[test1_2021-03-16_10-46-06.log](https://github.com/kingToolbox/WindTerm/files/6151229/test1_2021-03-16_10-46-06.log)

Attached is the logs during the process

**Comment by kingToolbox** [comment]
Thank you. This log does not contain debugging information, maybe you chose `Log printable output` instead of `Log all session output`. But it doesn't matter, you can use the following simpler steps to quickly collect again:

- Open session and execute `seq 1 100`.
- Check menu "Main Menu - Mode - Debug Mode".
- Execute `clear`, `seq 1 100`, `clear.`
- Uncheck menu "Main Menu - Mode - Debug Mode".
- Click the menu item "Right click menu - Log - Open Log Folder".
- Open the folder `debug` and confirm that the latest log file exists and contains content such as "erasescreen".
- Upload your log file in your comment here. You can zip it before upload.

Sorry to trouble you, I cannot reproduce it in multiple environments, and no other users have reported this issus.

**Comment by rpulikool** [comment]
you can go ahead an close this issue, it was a random issue observed on a machine. I tried on multiple other laptop and it didn't repeated

**Comment by kingToolbox** [comment]
Thank you for testing on other machines. I guess it is related to the SSH version of the server. If it still recurs, please reopen this issue. Thanks a lot.
