### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by darkhandz** [kingToolbox/WindTerm#629]
Hi, crash log attached, please have a look.

[WindTerm.zip](https://github.com/kingToolbox/WindTerm/files/8398152/WindTerm.zip)
Windows 10, 2.4.0 Pre1

**Comment by kingToolbox** [comment]
Duplicate of #553 

Thank you for your logs. It does cause a crash when executing `Clear the screen` in a disconnected dumb session. This bug has been confirmed and fixed in the `WindTerm_2.4.0_Prerelease_2` version. the new prerelease version will be released in two or three days. Please stay tuned.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

**Comment by darkhandz** [comment]
Thank you for your hard work, I had try pre2, it will not crash anymore.
