### ISSUE TITLE
Can WindTerm add an indicator to view the encryption algorithm used by the SSH connection?

### ISSUE THREAD

**Issue by loutelecom** [kingToolbox/WindTerm#652]

**Comment by kingToolbox** [comment]
Sure. I will add this feature in the next `WindTerm_2.5.0` version.

**Comment by kingToolbox** [comment]
Sorry, I checked the relevant code and found it very cumbersome to implement. Since this feature is not necessary, and most SSH clients do not provide such a feature, I decided to abandon the development of this feature. Please understand.

If you really need to see the relevant login details, you can log and read the details from the log.
