### ISSUE TITLE
Auto login failed, please try again.

### ISSUE THREAD

**Issue by karagi4** [kingToolbox/WindTerm#70]
WindTerm 2.0.2
Auto login failed, please try again.
![2021-04-01 18-54-29 WindTerm](https://user-images.githubusercontent.com/41114204/113321116-f2182200-931b-11eb-83f6-3a4600f95030.jpg)

**Comment by karagi4** [comment]
In version 2.0.2, this error appeared and it does not go away!

**Comment by kingToolbox** [comment]
In order to fix 2FA login issue in version 2.0.2, almost the entire automatic login module was rewritten. Although rigorous testing has been performed, new errors may have been introduced :(

So, what does this automatic login include? Is it a password, a public-key, a keyboard-interactive, or a mix? Is this automatic login created by copying the `profile` folder from the old version, or is it generated by selecting `Auto login next time` when logging in in the 2.0.2 version? 

In addition, please follow the steps below to see if the issue can be fixed:
- Open the session property dialog, then click `SSH - Authentication - Saved automatic authentication - Clear button` to clear the auto login.
- Restart the session and log in with `Auto login next time` checked.
- Restart the session again to see if it can be automatically logged in successfully.

**Comment by karagi4** [comment]
![image](https://user-images.githubusercontent.com/41114204/113340752-f3097d80-9334-11eb-8fd3-2bfca6672063.png)

I use this, the login happens, but the next time it asks for confirmation again.

**Comment by karagi4** [comment]
I also removed the session.autoLogin parameter in the user.sessions file but it doesn't help, authorization is still requested
![image](https://user-images.githubusercontent.com/41114204/113342777-922f7480-9337-11eb-9901-fc71aec3d579.png)

**Comment by karagi4** [comment]
From version 1.9 to 2.0.1, the profile migrated well. Version 2.0.1 works and does not ask for re-confirmation

**Comment by karagi4** [comment]
On a new installation of version 2.0.2 without transferring settings, when connecting via an ssh key, auto-login also does not work :(

**Comment by kingToolbox** [comment]
If my understanding is correct, do you mean that you cannot use `pageant` to automatically log in? This problem does exist, I have reproduced it just now, and will fix it as soon as possible.

It just so happens that the X/Y/Z modem feature is almost finished, so I will wait for the X/Y/Z modem to be released together. The release time is expected this weekend. I will update the progress here, thank you very much!

**Comment by karagi4** [comment]
Yes, thank you!

**Comment by karagi4** [comment]
Also, since we are talking about authorization, could you implement the possibility of enabling a Master password to log in to the WindTerm application?
Then I would use the built-in WindTerm authorization. I use Pageant and the master password for the key in it. If you use this in WindTerm, you have to enter the master password every time you connect.

**Comment by kingToolbox** [comment]
WindTerm already has a master password :smile: You can read [master password](https://kingtoolbox.github.io/2021/03/11/protection-master-password/) to learn more. But if this is not what you want, you can describe your needs in more detail, and I will try to implement it.

**Comment by karagi4** [comment]
![2021-04-03 15-29-52 WindTerm](https://user-images.githubusercontent.com/41114204/113478479-ad15fc00-9491-11eb-8e79-66279e6ef76b.jpg)
Yes, this is suggested at the first launch. But if I already have downloaded sessions or I previously refused to set the master password, then I can no longer set it. Or how it can be done, maybe I don't know it?

**Comment by karagi4** [comment]
About the master password. I had in mind the possibility of setting the master password to log in to WindTerm completely, so that if I do not enter the password, I would not be able to use WindTerm and see the configured connections at all.

**Comment by karagi4** [comment]
Or the second option is an analogue of pageant Putty, so that I can enter the password on the ssh key only once and that it no longer requires confirmation of the input in each session until I restart WindTerm

**Comment by karagi4** [comment]
Thank you for your feedback!

**Comment by kingToolbox** [comment]
> But if I already have downloaded sessions or I previously refused to set the master password, then I can no longer set it. Or how it can be done, maybe I don't know it?

Sorry, currently it can only be set for the first time. The method of re-setting and modification will be provided in later versions. 

> I had in mind the possibility of setting the master password to log in to WindTerm completely, so that if I do not enter the password, I would not be able to use WindTerm and see the configured connections at all.

Speaking of this feature, I happen to be completing a new function "lock screen", just like the "lock screen" of Windows or Linux. During use, you can lock the screen at any time, and then you must unlock it to continue operation, otherwise you cannot see the currently opened tabs, screen output, etc, which just meet some of your needs. 

But this feature "lock screen" is more used to protect the current screen output to prevent others from peeping on the screen when you are not in front of the computer, and not used to protect youre session configuration, because the configuration itself 'windterm-install-path/profile/default.v10/terminal/user.sessions' is stored on the disk and is not encrypted and can be viewed at any time with a text editor. Unless encrypted, I also think it is meaningless to protect any content on the disk because it can be viewed with third-party tools. In other words, if your computer is hacked, then any information will be at risk. This is not something that WindTerm or other clients can solve.  

> the second option is an analogue of pageant Putty, so that I can enter the password on the ssh key only once and that it no longer requires confirmation of the input in each session until I restart WindTerm

Isn't this the current design? :smiley:  `After the first setting, you will only be asked when WindTerm need to read encrypted information such as automatic login, and the input will be valid until WindTerm is closed.`

**Comment by kingToolbox** [comment]
Sorry to keep you waiting. [WindTerm_2.1.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has finally been released and this automatically login issue has been fixed. You can download and check it now. Thank you.

`X/Y/Z modem` and `lock screen` are still under development and are not stable yet, so it will take a few days. This is also the reason why the version 2.1.0_Prerelease_1 has not been released last weekend and has been delayed so far.

**Comment by karagi4** [comment]
In Winterm v2.1.0, autologin works.
It was possible to set the master password and transfer the sessions like this: When running a clean version of WindTerm, we set the master password, and then copy the following files from the working WindTerm configuration with replacement:...\WindTerm\profiles\default.v10\global\reopen.history
…\WindTerm\profiles\default.v10\terminal
After that, your sessions and settings should be transferred to a clean WindTerm with a master password.

**Comment by kingToolbox** [comment]
Unfortunately, for security, WindTerm will generate a unique fingerprint in the `profile` the first time it is created, and this fingerprint will participate in all subsequent encryption. Therefore, the `profile` of different WindTerms are not interchangeable.

However, when developing the `lock screen` feature, the feature of changing the master password has been implemented. The only problem now is that the current security design makes it impossible for even WindTerm to know whether the master password to be replaced is correct.

In daily use, this is not a problem. WindTerm is responsible for decrypting using the master password given by the user and sending the decrypted authentication information to the server for judgment. WindTerm itself does not know, nor does it need to know whether the decrypted information is correct. But when changing the master password, WindTerm needs to determine whether the decrypted information is correct, otherwise after re-encrypting the wrong decrypted data with the new master password, All the user's automatic login data will be lost. 

I am still thinking about how to better solve this problem, and I also hope you can share more suggestions. Thank you very much for your great advice.

**Comment by kingToolbox** [comment]
The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released, and supports [locking screen](https://kingtoolbox.github.io/2021/04/23/lock-screen/) and [changing the master password](https://kingtoolbox.github.io/2021/04/23/change-master-password/), you can download and check it now, thank you!
