### ISSUE TITLE
Request: Drag&Drop in the Filer widget

### ISSUE THREAD

**Issue by ImMartinYoung** [kingToolbox/WindTerm#756]
Version 2.4.1 has provided nearly everything for a Linux admin, except the "drag%drop" property in the Filer widget. We hope this property would come forth in next version.

Thank you so much!

**Comment by kingToolbox** [comment]
Sorry for the late reply.

Do you mean uploading and downloading files by drag and drop? Currently, uploading by dragging and dropping is supported, but downloading is not yet supported. Downloading requires dealing with the system, such as `Windows Shell`. Since WindTerm is cross-platform, it needs to be implemented system by system. I will provide this feature in subsequent releases, please stay tuned, thank you.

**Comment by ImMartinYoung** [comment]
> Sorry for the late reply.
> 
> Do you mean uploading and downloading files by drag and drop? Currently, uploading by dragging and dropping is supported, but downloading is not yet supported. Downloading requires dealing with the system, such as `Windows Shell`. Since WindTerm is cross-platform, it needs to be implemented system by system. I will provide this feature in subsequent releases, please stay tuned, thank you.

Yes, uploading files works fine. That already fulfills my need. Rarely use downloading. Now uninstall my mobaxterm. Cool!

Thank you so much!

**Comment by kingToolbox** [comment]
Ok, Please don't forget to continue to update the new versions of `WindTerm`, there are still many wonderful features under development, such as [Auto completion](https://kingtoolbox.github.io/2022/05/18/auto_completion/), [Command Snippet](https://github.com/kingToolbox/WindTerm/issues/239#issuecomment-951934488), `Trigger` and so on. :smile:
