### ISSUE TITLE
How to set the shortcut for copy view (copy current session)?

### ISSUE THREAD

**Issue by fmlijl** [kingToolbox/WindTerm#770]
WindTerm experience is very good, but there is a shortcut that can't be set, how to set the shortcut for copy view (copy current session)?

**Comment by kingToolbox** [comment]
In `WindTerm`, you can customize the shortcut keys for any menu item. Please follow the steps below:

- Open the file `WindTerm_install_path/global/king.actions` and find the corresponding action `Window.DuplicateView` according to the text `Duplicate View` in the menu.
- Open the file `WindTerm_install_path/global/king.keymaps` and add a configuration item:
``` json
 { "keys": "<Ctrl+Shift+D>",
    "modes": "local, remote",
    "when": "window.isScope('terminal.*')",
    "action": "Window.DuplicateView"
  },
```
You can use any key you like instead of `Ctrl+Shift+D`.
- Restart to take effect. 

Please read [this comment](https://github.com/kingToolbox/WindTerm/issues/13#issuecomment-664813314) to learn more, thank you.

BTW:
This shortcut key `Ctrl+Shift+D` has been officially bound to `Window.DuplicateView` and will be released in `WindTerm_2.5.0_Prerelease_2`.

**Comment by fmlijl** [comment]
Thank you for your reply, I don't immediately check your message. Follow your steps, I found the wind.actions and wind.keymaps in `WindTerm_install_path/global` directory instead of king.actions and king.keymaps. But eventually I was able to modify it and apply my settings.

**Comment by fmlijl** [comment]
> In `WindTerm`, you can customize the shortcut keys for any menu item. Please follow the steps below:
> 
> * Open the file `WindTerm_install_path/global/king.actions` and find the corresponding action `Window.DuplicateView` according to the text `Duplicate View` in the menu.
> * Open the file `WindTerm_install_path/global/king.keymaps` and add a configuration item:
> 
> ```json
>  { "keys": "<Ctrl+Shift+D>",
>     "modes": "local, remote",
>     "when": "window.isScope('terminal.*')",
>     "action": "Window.DuplicateView"
>   },
> ```
> 
> You can use any key you like instead of `Ctrl+Shift+D`.
> 
> * Restart to take effect.
> 
> Please read [this comment](https://github.com/kingToolbox/WindTerm/issues/13#issuecomment-664813314) to learn more, thank you.
> 
> BTW: This shortcut key `Ctrl+Shift+D` has been officially bound to `Window.DuplicateView` and will be released in `WindTerm_2.5.0_Prerelease_2`.

Thank you for your reply, I don't immediately check your message. Follow your steps, I found the wind.actions and wind.keymaps in `WindTerm_install_path/global` directory instead of king.actions and king.keymaps. But eventually I was able to modify it and apply my settings.
