### ISSUE TITLE
By default, the built-in shell terminal adds the parameter -l（内置shell终端默认添加参数：-l）

### ISSUE THREAD

**Issue by GanHuaLin** [kingToolbox/WindTerm#781]
参考了一下其他终端应用，添加参数：-l
<img width="531" alt="iShot_2022-05-24_10 46 32" src="https://user-images.githubusercontent.com/8326761/169939223-f11ac4f9-e235-44be-9148-77519be2c17f.png">

_Originally posted by @GanHuaLin in https://github.com/kingToolbox/WindTerm/issues/753#issuecomment-1135344094_

**Comment by kingToolbox** [comment]
Thank you very much. After commenting on #753 that day, I also accidentally saw that adding `--login` or `-l` and `-i` can solve the problem. So this has been done and will be released with the new `WindTerm_2.5.0_Prerelease_2` version. Please download and try it then. Thank you.

**Comment by kingToolbox** [comment]
Sorry for replying so late, I just got back from a business trip.

This issue has been fixed in the [WindTerm_2.5.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.5.0) version. In this version, `--login` or `-l` and `-i` will be automatically added as parameters when generating the `shell` session. Please download and try it, thank you.
