### ISSUE TITLE
Feature suggestions: Pin tabs

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindTerm#82]
I have used many SSH clients before,such as xshell /finalshell/securecrt... and open multiple tabs and switch tab frequently, so I hope to have some shortcut keys for tabs switch:

here is my suggestion, For me, these can improve efficiency .

1. tab auto switch when mouse on it, like hover over the tab for 2 sec;

2. tab switch use shortcuts,like Alt+1~9  or Ctrl+Tab  or Shift+Tab;

3. Allow pin tabs;

Thanks for the great software.

**Comment by kingToolbox** [comment]
Thank you, these proposals look great. 

1. tab auto switch when mouse on it, like hover over the tab for 2 sec;
WindTerm supported this feature a long time ago :smile: , but it was disabled. It has been redesigned as an option, and you can enable it in the new version 2.1.0-prerelease-2. 

2. tab switch use shortcuts,like Alt+1~9 or Ctrl+Tab or Shift+Tab;
Please try `alt+[` and `alt+]`, it should be the `Ctrl+Tab` and `Shift+Tab` you want. In the past two days, the feature of switching to the tab index has also been developed and used the shortcut key `Ctrl+Shift+0~9`.
`Shift+Tab` has been used to decrease the indentation in WindEdit, and `Alt+1~9` has been used to trigger the menu items of the main menu. So they are not very suitable for tabs. Of course, you can assign any shortcut keys as you like. For details, please refer to #13. 

3. Allow pin tabs;
Since the entire interface framework will be replaced in the future, this feature will not be done for the time being and will be reserved for subsequent development.

**Comment by gooker** [comment]
Awesome. I've recommended WindTerm to my friends。


> Thank you, these proposals look great.
> 
> 1. tab auto switch when mouse on it, like hover over the tab for 2 sec;
>    WindTerm supported this feature a long time ago 😄 , but it was disabled. It has been redesigned as an option, and you can enable it in the new version 2.1.0-prerelease-2.
> 2. tab switch use shortcuts,like Alt+1~9 or Ctrl+Tab or Shift+Tab;
>    Please try `alt+[` and `alt+]`, it should be the `Ctrl+Tab` and `Shift+Tab` you want. In the past two days, the feature of switching to the tab index has also been developed and used the shortcut key `Ctrl+Shift+0~9`.
>    `Shift+Tab` has been used to decrease the indentation in WindEdit, and `Alt+1~9` has been used to trigger the menu items of the main menu. So they are not very suitable for tabs. Of course, you can assign any shortcut keys as you like. For details, please refer to #13.
> 3. Allow pin tabs;
>    Since the entire interface framework will be replaced in the future, this feature will not be done for the time being and will be reserved for subsequent development.

**Comment by kingToolbox** [comment]
The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and supports selecting tabs by hovering or using the shortcut key `Ctrl+Shift+0~9`. Please download and check, thank you!

**Comment by gooker** [comment]
> The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and supports selecting tabs by hovering or using the shortcut key `Ctrl+Shift+0~9`. Please download and check, thank you!

P2 OK.thanks

**Comment by kingToolbox** [comment]
Thank you for verifying so quickly. The feature "Pin tabs" will be developed after the UI framework is replaced, and it is expected to be in the second half of the year. Please keep follow, thank you!

**Comment by yangjq4** [comment]
I'm not used to tab auto switch  by mouse hover on, so is there any configuration to disable this?

**Comment by gooker** [comment]
> I'm not used to tab auto switch when mouse hover on, so is there any configuration to disable this?

I think you can try:
delete global/wind.config
  _"tabbar.hoverToSelect": 0.2,_

**Comment by kingToolbox** [comment]
Yes, of course. The most important thing to make a tool is to meet the different needs of all users for the same feature. :smile: Please open or create `WindTerm-install-path/default.v10/user.config` and add:
``` json
{
   ...
   "tabbar.hoverToSelect": 0,
   ...
}
```
You can modify the same configuration in `WindTerm-install-path/global/wind.config` too, but when you upgrade to a new version, you need to modify it again. The settings GUI will be implemented in the next version.

**Comment by kingToolbox** [comment]
Hi, gooker, may I ask if you usually count tabs by yourself when you use shortcut keys `Alt+1~9` to switch tabs? Would it be worthwhile to add index numbers to tab titles for convenience at the cost of increasing the width of the tabs? Thank you!

**Comment by gooker** [comment]
> Hi, gooker, may I ask if you usually count tabs by yourself when you use shortcut keys `Alt+1~9` to switch tabs? Would it be worthwhile to add index numbers to tab titles for convenience at the cost of increasing the width of the tabs? Thank you!

1,Most of the time I use mouse, "mouse hover" is very easy to use;

2,When using the keyboard, ALT + 0 ~ 9 is only for single view, so I use Alt + [/]
If Alt + 0 ~ 9 for all tags, add index number will be very useful. I will also get used to using Alt + 0 ~ 9. Increasing the width is ok.

> i remove menu shortcut , change ctrl+shift+num  to alt+num :memo:

![20210428093808](https://user-images.githubusercontent.com/5688076/116333178-9bf8aa80-a805-11eb-8026-e7a698d3f9ce.png)

**Comment by kingToolbox** [comment]
Thank you for such a detailed answer.

After considering your suggestions, I have just finished this feature. Now you can set the numbers to be displayed on all tabs or the first to ninth tabs, or not to display at all in the next prerelease version. Because `Alt+[` and `Alt+]` can already switch tabs between different groups, I still keep `Ctrl+Shift+1~9` only switch tabs in the current group to meet different needs. I think this design would be better.

**Comment by kingToolbox** [comment]
@gooker 
After redesigning the menu bar, [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) finally support `Alt+0~5` shortcut keys to activate tabs by default. :smile: Please download and use it, thank you.

BTW:

Alt+0: Activate the last tab.
Alt+1~5: Activate the first to fifth tabs.

And shortcut keys such as `Ctrl+Shift+0~9` have been removed.

**Comment by lbmeng** [comment]
I can't find a setting in GUI to disable Tab hovering switch in WindTerm 2.5.0.

Is onfig file change the only way to do this for now?

**Comment by gooker** [comment]
> I can't find a setting in GUI to disable Tab hovering switch in WindTerm 2.5.0.
> 
> Is onfig file change the only way to do this for now?

<img width="471" alt="1676012367487" src="https://user-images.githubusercontent.com/5688076/218024022-cbc70658-76cc-4b28-b023-9957eeb19b7d.png">
