### ISSUE TITLE
2.1.0 p1  search bug 

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindTerm#83]
![20210415110118](https://user-images.githubusercontent.com/5688076/115170710-e0909180-a0f3-11eb-81db-9ca0d4bd4939.png)

waiting for next version.

**Comment by kingToolbox** [comment]
@gooker Hello, I finally fixed the problem in [WindTerm_2.1.0_Prerelase_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease). Please download and check it. Thank you.

BTW, the reason for this problem is that when there is a very long string in the `find` combo box, the combo box will become very wide, even beyond the screen, which is a bad feature of QComboBox in my opinion.

**Comment by gooker** [comment]
> @gooker Hello, I finally fixed the problem in [WindTerm_2.1.0_Prerelase_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease). Please download and check it. Thank you.
> 
> BTW, the reason for this problem is that when there is a very long string in the `find` combo box, the combo box will become very wide, even beyond the screen, which is a bad feature of QComboBox in my opinion.

test ok!

**Comment by kingToolbox** [comment]
Thank you! :smile:
