### ISSUE TITLE
What are local mode and remote mode?

### ISSUE THREAD

**Issue by leafgrey** [kingToolbox/WindTerm#851]
想问下 模式 里面 本地模式 和远程模式是什么意思

**Comment by xzhuiz** [comment]
本地模式就是离线模式，相当于文本编辑器

**Comment by kingToolbox** [comment]
The `local mode` is mainly used for browsing the text. In local mode, every key pressed will be parsed locally instead of sending to the server. Especially when there is a large amount of output, pressing the `Alt+Enter` key to enter `local mode` can immediately stop the scrolling of the screen.

For a more detailed description, please refer to [Local Mode](https://kingtoolbox.github.io/tags/local-mode/).
