### ISSUE TITLE
I want to turn off the associative function of the command

### ISSUE THREAD

**Issue by makexiao113** [kingToolbox/WindTerm#886]
Windterm is always associating with wrong commands, so I want to turn off it, but I can't find it in Settings

**Comment by kingToolbox** [comment]
Sorry for the inconvenience caused by this feature. You can open `Menubar - Preferences - Settings Dialog - Terminal - Auto Completion` and set it.

However, if you can describe your input and expected output in more detail, as well as candidates for autocomplete at this time. I will be very grateful. Autocomplete should be a very useful feature, but it still needs to be polished and improved. So I need to get more usage samples to improve it.

**Comment by makexiao113** [comment]
> Sorry for the inconvenience caused by this feature. You can open `Menubar - Preferences - Settings Dialog - Terminal - Auto Completion` and set it.
> 
> However, if you can describe your input and expected output in more detail, as well as candidates for autocomplete at this time. I will be very grateful. Autocomplete should be a very useful feature, but it still needs to be polished and improved. So I need to get more usage samples to improve it.

thank you！ 
Previous versions of windTerm did not correctly associate simplified commands such as 'll' or non-standard commands installed on operating system applications such as ‘mysql’，‘telnet’,'firewall'.
