### ISSUE TITLE
Turn off address bar and highlighting

### ISSUE THREAD

**Issue by Shellfishgene** [kingToolbox/WindTerm#92]
Hi!
Can I turn off the address bar? And the highlighting of text on single click?

**Comment by kingToolbox** [comment]
Yes, you can. Please open the configuration file `WindTerm-install-path/terminal/configs/toolbar.config` and find:
``` json
  "Standard" : [
    { "Action" : "Terminal.NewSession", "Menu" : "Open Recent"},
    { "Action" : "Terminal.DisconnectSession" },
    { "Action" : "Terminal.ReconnectSession" },
    { "AddressBar" : true },
    { "Action" : "Window.ToggleToolbarPopup", "Popup" : "KitPopup" }
  ],
```
Delete the `AddressBar` item if you need to not display the address bar, or delete the whole `Standard` item if you need to not display the entire toolbar.

It's easier to cancel the highlighting of a word. Please open or create `WindTerm-install-path/profiles/default.v10/user.config` and add json item:
{
  "text.highlightCaretWord": false
}
The setting UI will be provided in the version v2.2.0 in May or June.

**Comment by Shellfishgene** [comment]
Thanks! The setting for the word highlighting is `terminal.text.highlightCaretWord`, in case anyone else needs this.

**Comment by kingToolbox** [comment]
Yes, all `text.*` options except `text.zoomFactor` have three forms. Take `text.highlightCaretWord` as an example, there are `text.highlightCaretWord`, `terminal.text.highlightCaretWord` and `editor.text.highlightCaretWord` respectively.

WindTerm only reads `text.highlightCaretWord` and `terminal.text.highlightCaretWord`, and [WindEdit](https://github.com/kingToolbox/WindTerm) only reads `text.highlightCaretWord` and `editor.text.highlightCaretWord`. Both `terminal.text.highlightCaretWord` and `editor.text.highlightCaretWord` have higher priority than `text.highlightCaretWord`.

The reason for this design is that WindTerm and WindEdit are completely a whole program during development. However, due to a separate release, WindTerm does not contain WindEdit, and vice versa, so the design loses its meaning. In WindTerm, You only need to set `text.*` and make sure that `terminal.text.*` does not exist. 

Once setup GUI development is completed, everyone can easily modify the settings without knowing these trivial design details. :smile:
